// Generated by scripts/generate.ts from public/spec/0.1/schemas. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

import type { AnySchemaObject } from "ajv/dist/2020.js";

export const schemas: Record<string, AnySchemaObject> = {
  "core": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.1:core",
    "title": "HOS Core 0.1",
    "description": "Draft. The operational minimum required to make the arrival-readiness scenario portable: identifiers, external references, extensions, sensitivity classes, the Unit status model and nine Core entities. This file holds definitions; HOS Events reference them.",
    "$defs": {
      "hosId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "Opaque, stable HOS identifier, unique within its Tenant. It carries no business meaning and no personal data."
      },
      "ianaTimezone": {
        "type": "string",
        "pattern": "^[A-Za-z]+(?:[/_+-][A-Za-z0-9]+)*$",
        "description": "IANA time zone name, for example Europe/Paris."
      },
      "countryCode": {
        "type": "string",
        "pattern": "^[A-Z]{2}$",
        "description": "ISO 3166-1 alpha-2 country code."
      },
      "localTime": {
        "type": "string",
        "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$",
        "description": "Local wall-clock time, HH:MM."
      },
      "externalRef": {
        "type": "object",
        "description": "A typed, sourced reference to an identifier held by another system.",
        "required": [
          "source_system",
          "id_type",
          "source_id"
        ],
        "properties": {
          "source_system": {
            "type": "string",
            "format": "uri",
            "description": "URI of the system that issued the identifier."
          },
          "id_type": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9_]*$",
            "description": "Kind of identifier in that system, for example confirmation_number."
          },
          "source_id": {
            "type": "string",
            "minLength": 1,
            "description": "The identifier as issued by the source system."
          },
          "verification": {
            "enum": [
              "verified",
              "asserted"
            ],
            "description": "verified when the identifier was confirmed with the source system; asserted when it is only reported. Omitted when not known."
          }
        },
        "additionalProperties": false
      },
      "externalRefs": {
        "type": "array",
        "items": {
          "$ref": "#/$defs/externalRef"
        }
      },
      "extensions": {
        "type": "object",
        "description": "Vendor detail under an inverted domain namespace such as com.example. Each namespace publishes its own schema and documentation, and can never redefine a Core field or enum.",
        "propertyNames": {
          "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
        },
        "additionalProperties": {
          "type": "object"
        }
      },
      "sensitivityClass": {
        "enum": [
          "public",
          "internal",
          "confidential",
          "restricted"
        ],
        "description": "Handling class. public: no restriction; internal: operational data for authorised participants; confidential: commercial or pseudonymous personal data; restricted: data whose disclosure could harm a person, such as special-category data."
      },
      "unitStatusDimension": {
        "enum": [
          "occupancy",
          "housekeeping",
          "maintenance",
          "commercial"
        ],
        "description": "The four independent dimensions of a Unit's status."
      },
      "occupancyStatus": {
        "enum": [
          "vacant",
          "occupied",
          "unknown"
        ],
        "description": "Physical occupancy state."
      },
      "housekeepingStatus": {
        "enum": [
          "dirty",
          "clean",
          "inspected",
          "unknown"
        ],
        "description": "Readiness as reported by the housekeeping authority."
      },
      "maintenanceStatus": {
        "enum": [
          "operational",
          "out_of_service",
          "unknown"
        ],
        "description": "Basic operational availability; there is no detailed maintenance model in 0.1."
      },
      "commercialStatus": {
        "enum": [
          "sellable",
          "not_sellable",
          "unknown"
        ],
        "description": "Commercial disposition as declared by the responsible system."
      },
      "unitStatuses": {
        "type": "object",
        "description": "Values of one or more Unit status dimensions.",
        "minProperties": 1,
        "properties": {
          "occupancy": {
            "$ref": "#/$defs/occupancyStatus"
          },
          "housekeeping": {
            "$ref": "#/$defs/housekeepingStatus"
          },
          "maintenance": {
            "$ref": "#/$defs/maintenanceStatus"
          },
          "commercial": {
            "$ref": "#/$defs/commercialStatus"
          }
        },
        "additionalProperties": false
      },
      "maintenanceWindowStatuses": {
        "type": "object",
        "description": "The Unit statuses a maintenance window imposes while it lasts: maintenance out_of_service when the unit cannot be used, commercial not_sellable when it cannot be sold.",
        "minProperties": 1,
        "properties": {
          "maintenance": {
            "const": "out_of_service"
          },
          "commercial": {
            "const": "not_sellable"
          }
        },
        "additionalProperties": false
      },
      "maintenanceReason": {
        "enum": [
          "repair",
          "renovation",
          "internal_use",
          "other"
        ],
        "description": "Why a maintenance window exists, when the source says."
      },
      "reservationStatus": {
        "enum": [
          "tentative",
          "confirmed",
          "cancelled",
          "no_show"
        ],
        "description": "Commercial status of a Reservation."
      },
      "stayStatus": {
        "enum": [
          "expected",
          "in_house",
          "departed",
          "cancelled"
        ],
        "description": "Operational status of a Stay."
      },
      "taskType": {
        "enum": [
          "cleaning",
          "inspection",
          "turndown",
          "maintenance",
          "other"
        ]
      },
      "taskStatus": {
        "enum": [
          "open",
          "in_progress",
          "completed",
          "cancelled"
        ]
      },
      "taskPriority": {
        "enum": [
          "low",
          "normal",
          "high",
          "urgent"
        ]
      },
      "messageChannel": {
        "enum": [
          "sms",
          "email",
          "chat",
          "messaging_app",
          "ota_messaging",
          "phone",
          "other"
        ]
      },
      "Tenant": {
        "title": "Tenant",
        "description": "Security, policy and data-autonomy boundary.",
        "x-hos-boundary": "A Property belongs to one Tenant at a time.",
        "type": "object",
        "required": [
          "tenant_id"
        ],
        "properties": {
          "tenant_id": {
            "$ref": "#/$defs/hosId"
          }
        },
        "additionalProperties": false
      },
      "Property": {
        "title": "Property",
        "description": "Tenant, IANA time zone, country, business-date policy and standard check-in and check-out times.",
        "x-hos-boundary": "Establishment-level operating context.",
        "type": "object",
        "required": [
          "property_id",
          "tenant_id",
          "timezone",
          "country",
          "business_date_policy"
        ],
        "properties": {
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "tenant_id": {
            "$ref": "#/$defs/hosId"
          },
          "timezone": {
            "$ref": "#/$defs/ianaTimezone"
          },
          "country": {
            "$ref": "#/$defs/countryCode"
          },
          "business_date_policy": {
            "type": "object",
            "required": [
              "rollover_local_time"
            ],
            "properties": {
              "rollover_local_time": {
                "$ref": "#/$defs/localTime",
                "description": "Local time at which the business date advances, for example 04:00 after night audit."
              }
            },
            "additionalProperties": false
          },
          "standard_check_in_time": {
            "$ref": "#/$defs/localTime",
            "description": "Local time at which a stay starts when a source plans stays in days, for example 15:00."
          },
          "standard_check_out_time": {
            "$ref": "#/$defs/localTime",
            "description": "Local time at which a stay ends when a source plans stays in days, for example 11:00."
          },
          "external_refs": {
            "$ref": "#/$defs/externalRefs"
          }
        },
        "additionalProperties": false
      },
      "Unit": {
        "title": "Unit",
        "description": "Property, local label or type, and four independent statuses.",
        "x-hos-boundary": "A room is a local type or label of Unit.",
        "type": "object",
        "required": [
          "unit_id",
          "property_id",
          "statuses"
        ],
        "properties": {
          "unit_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "label": {
            "type": "string",
            "minLength": 1,
            "description": "Local label, for example 204."
          },
          "unit_type": {
            "type": "string",
            "minLength": 1,
            "description": "Local type, for example double_room."
          },
          "statuses": {
            "allOf": [
              {
                "$ref": "#/$defs/unitStatuses"
              }
            ],
            "required": [
              "occupancy",
              "housekeeping",
              "maintenance",
              "commercial"
            ]
          },
          "external_refs": {
            "$ref": "#/$defs/externalRefs"
          }
        },
        "additionalProperties": false
      },
      "MaintenanceWindow": {
        "title": "Maintenance window",
        "description": "A planned period when a Unit is out of service or cannot be sold: a repair, a renovation or internal use. Its statuses say which dimensions it affects.",
        "x-hos-boundary": "A plan. What holds now is the Unit's maintenance and commercial status.",
        "type": "object",
        "required": [
          "maintenance_id",
          "property_id",
          "unit_id",
          "starts_at",
          "ends_at",
          "statuses"
        ],
        "properties": {
          "maintenance_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "#/$defs/hosId"
          },
          "starts_at": {
            "type": "string",
            "format": "date-time",
            "description": "Start of the window. When the source plans windows in days, the window holds the unit as a stay would: its first day at the Property's standard check-in time."
          },
          "ends_at": {
            "type": "string",
            "format": "date-time",
            "description": "End of the window, exclusive. When the source plans windows in days, the day that frees the unit at the Property's standard check-out time."
          },
          "statuses": {
            "$ref": "#/$defs/maintenanceWindowStatuses"
          },
          "reason": {
            "$ref": "#/$defs/maintenanceReason"
          },
          "cancelled_at": {
            "type": "string",
            "format": "date-time",
            "description": "When the window was withdrawn, if it was."
          },
          "external_refs": {
            "$ref": "#/$defs/externalRefs"
          }
        },
        "additionalProperties": false
      },
      "Reservation": {
        "title": "Reservation",
        "description": "Property, commercial status, planned arrival and departure, and external references.",
        "x-hos-boundary": "Commercial commitment; it can yield zero, one or many Stays.",
        "type": "object",
        "required": [
          "reservation_id",
          "property_id",
          "status",
          "planned_arrival_date",
          "planned_departure_date"
        ],
        "properties": {
          "reservation_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "status": {
            "$ref": "#/$defs/reservationStatus"
          },
          "planned_arrival_date": {
            "type": "string",
            "format": "date"
          },
          "planned_departure_date": {
            "type": "string",
            "format": "date"
          },
          "guest_id": {
            "$ref": "#/$defs/hosId"
          },
          "external_refs": {
            "$ref": "#/$defs/externalRefs"
          }
        },
        "additionalProperties": false
      },
      "Stay": {
        "title": "Stay",
        "description": "Property, linked Reservation, planned and actual times, and Unit assignment history. A reservation for several units yields one Stay per unit.",
        "x-hos-boundary": "Operational execution of a visit.",
        "type": "object",
        "required": [
          "stay_id",
          "property_id",
          "reservation_id",
          "status",
          "planned_arrival_at",
          "planned_departure_at",
          "unit_assignments"
        ],
        "properties": {
          "stay_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "reservation_id": {
            "$ref": "#/$defs/hosId"
          },
          "status": {
            "$ref": "#/$defs/stayStatus"
          },
          "guest_id": {
            "$ref": "#/$defs/hosId"
          },
          "planned_arrival_at": {
            "type": "string",
            "format": "date-time"
          },
          "planned_departure_at": {
            "type": "string",
            "format": "date-time"
          },
          "actual_arrival_at": {
            "type": "string",
            "format": "date-time"
          },
          "actual_departure_at": {
            "type": "string",
            "format": "date-time"
          },
          "unit_assignments": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "unit_id",
                "assigned_at"
              ],
              "properties": {
                "unit_id": {
                  "$ref": "#/$defs/hosId"
                },
                "assigned_at": {
                  "type": "string",
                  "format": "date-time"
                },
                "released_at": {
                  "type": "string",
                  "format": "date-time"
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      },
      "Task": {
        "title": "Task",
        "description": "Linked Property, Unit or Stay; type, status and priority.",
        "x-hos-boundary": "Minimal operational work item.",
        "type": "object",
        "required": [
          "task_id",
          "property_id",
          "task_type",
          "status",
          "priority"
        ],
        "properties": {
          "task_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "#/$defs/hosId"
          },
          "stay_id": {
            "$ref": "#/$defs/hosId"
          },
          "task_type": {
            "$ref": "#/$defs/taskType"
          },
          "status": {
            "$ref": "#/$defs/taskStatus"
          },
          "priority": {
            "$ref": "#/$defs/taskPriority"
          }
        },
        "additionalProperties": false
      },
      "Guest": {
        "title": "Guest",
        "description": "Pseudonymous HOS identifiers and external references only. A producer without a stable guest identity publishes no guest_id, and never derives one from names or contact details.",
        "x-hos-boundary": "No mandatory global person identity.",
        "type": "object",
        "required": [
          "guest_id"
        ],
        "properties": {
          "guest_id": {
            "$ref": "#/$defs/hosId"
          },
          "external_refs": {
            "$ref": "#/$defs/externalRefs"
          }
        },
        "additionalProperties": false
      },
      "Message": {
        "title": "Message",
        "description": "Channel, direction, time, linked Guest or Stay, and sensitivity class.",
        "x-hos-boundary": "Message content is excluded from Core.",
        "type": "object",
        "required": [
          "message_id",
          "property_id",
          "channel",
          "direction",
          "sent_at",
          "sensitivity"
        ],
        "properties": {
          "message_id": {
            "$ref": "#/$defs/hosId"
          },
          "property_id": {
            "$ref": "#/$defs/hosId"
          },
          "channel": {
            "$ref": "#/$defs/messageChannel"
          },
          "direction": {
            "enum": [
              "inbound",
              "outbound"
            ]
          },
          "sent_at": {
            "type": "string",
            "format": "date-time"
          },
          "guest_id": {
            "$ref": "#/$defs/hosId"
          },
          "stay_id": {
            "$ref": "#/$defs/hosId"
          },
          "sensitivity": {
            "$ref": "#/$defs/sensitivityClass"
          }
        },
        "additionalProperties": false
      },
      "GuestIdentityLink": {
        "title": "Guest identity link",
        "description": "A traceable, reversible relationship created when two guest references are matched. Resolution is never destructive: records are linked, not merged.",
        "type": "object",
        "required": [
          "link_id",
          "guest_id",
          "linked_to",
          "source",
          "confidence",
          "author",
          "rationale",
          "created_at"
        ],
        "properties": {
          "link_id": {
            "$ref": "#/$defs/hosId"
          },
          "guest_id": {
            "$ref": "#/$defs/hosId"
          },
          "linked_to": {
            "oneOf": [
              {
                "type": "object",
                "required": [
                  "guest_id"
                ],
                "properties": {
                  "guest_id": {
                    "$ref": "#/$defs/hosId"
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "object",
                "required": [
                  "external_ref"
                ],
                "properties": {
                  "external_ref": {
                    "$ref": "#/$defs/externalRef"
                  }
                },
                "additionalProperties": false
              }
            ]
          },
          "source": {
            "type": "string",
            "format": "uri",
            "description": "System that proposed the match."
          },
          "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "author": {
            "type": "string",
            "minLength": 1,
            "description": "Pseudonymous reference of the person or process responsible for the link."
          },
          "rationale": {
            "type": "string",
            "minLength": 1
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "revoked_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "event-envelope": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.1:event-envelope",
    "title": "HOS Events 0.1 envelope profile",
    "description": "Draft. CloudEvents 1.0 in structured JSON mode with HOS extension attributes. Every HOS event, and every reference situation, uses this envelope. Attribute names follow CloudEvents rules: lower-case letters and digits, at most 20 characters, scalar values only.",
    "type": "object",
    "required": [
      "specversion",
      "id",
      "source",
      "type",
      "time",
      "datacontenttype",
      "hosschemaversion",
      "hosrecordedat",
      "hostenant",
      "hosproperty",
      "hospropertytimezone",
      "hossubjects",
      "data"
    ],
    "propertyNames": {
      "pattern": "^[a-z0-9]{1,20}$"
    },
    "properties": {
      "specversion": {
        "const": "1.0",
        "description": "CloudEvents specification version."
      },
      "id": {
        "type": "string",
        "minLength": 1,
        "description": "Producer-scoped, immutable event identity. With source, it is the duplicate key: a redelivered event keeps its id."
      },
      "source": {
        "type": "string",
        "format": "uri",
        "description": "The producer. Must equal the producer declared in its Event Producer manifest."
      },
      "type": {
        "type": "string",
        "pattern": "^[a-z]+(?:_[a-z]+)*(?:\\.[a-z]+(?:_[a-z]+)*){1,2}$",
        "description": "Vendor-neutral HOS event type, named domain.resource.past_tense in the singular."
      },
      "time": {
        "type": "string",
        "format": "date-time",
        "description": "When the fact occurred, when known. Otherwise the best time the producer has, qualified by hostimebasis."
      },
      "datacontenttype": {
        "const": "application/json",
        "description": "HOS 0.1 data is always JSON."
      },
      "dataschema": {
        "type": "string",
        "format": "uri",
        "description": "Optional reference to the schema of data."
      },
      "hosschemaversion": {
        "const": "0.1",
        "description": "HOS version the event conforms to."
      },
      "hosrecordedat": {
        "type": "string",
        "format": "date-time",
        "description": "When the HOS implementation (producer or adapter) recorded the event. HOS always carries it."
      },
      "hostimebasis": {
        "enum": [
          "occurred",
          "modified",
          "recorded"
        ],
        "description": "What time represents. Absent means occurred. modified means the source's last modification of the entity, when it does not date the change itself: the fact occurred at or before time. recorded means the occurrence time is unknown and time is when the producer or adapter recorded the fact."
      },
      "hostenant": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Tenant: the security, policy and data-autonomy boundary."
      },
      "hosproperty": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Property the fact belongs to: the operating context."
      },
      "hospropertytimezone": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/ianaTimezone",
        "description": "IANA time zone of the Property. Local times are derived from it, never assumed."
      },
      "hosbusinessdate": {
        "type": "string",
        "format": "date",
        "description": "Local operating (business) date the fact belongs to, when it matters. It can differ from the calendar date of time."
      },
      "hossubjects": {
        "type": "string",
        "pattern": "^(?:tenant|property|unit|reservation|stay|task|guest|message):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}(?: (?:tenant|property|unit|reservation|stay|task|guest|message):[A-Za-z0-9][A-Za-z0-9._~-]{0,127})*$",
        "description": "Typed HOS entity references implicated by the fact, as space-separated type:id pairs, for example stay:stay_1042 unit:unit_204. A string because CloudEvents attributes cannot hold arrays."
      },
      "hosdatamode": {
        "enum": [
          "delta",
          "snapshot"
        ],
        "description": "How to read data. Absent means delta. A snapshot must be declared here, be allowed for its type and be sensitivity-classified."
      },
      "hossensitivity": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/sensitivityClass",
        "description": "Sensitivity class of data. Required for snapshots."
      },
      "hoscausationsource": {
        "type": "string",
        "format": "uri",
        "description": "Source of the event that caused this one, when known."
      },
      "hoscausationid": {
        "type": "string",
        "minLength": 1,
        "description": "Id of the event that caused this one, when known. Used with hoscausationsource."
      },
      "hosactor": {
        "type": "string",
        "pattern": "^(?:user|guest|system|integration):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "Who made the change in the producer, when it knows: user (a staff member), guest, system (the producer itself) or integration (another system through its API), with a pseudonymous, producer-scoped reference, for example user:staff_k3. Never a name or contact detail."
      },
      "data": {
        "type": "object",
        "description": "The normalized payload. Its shape is defined by type; vendor detail goes in data.extensions under an inverted domain namespace."
      }
    },
    "dependentRequired": {
      "hoscausationid": [
        "hoscausationsource"
      ],
      "hoscausationsource": [
        "hoscausationid"
      ]
    },
    "if": {
      "required": [
        "hosdatamode"
      ],
      "properties": {
        "hosdatamode": {
          "const": "snapshot"
        }
      }
    },
    "then": {
      "required": [
        "hossensitivity"
      ]
    }
  },
  "events": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.1:events",
    "title": "HOS Events 0.1",
    "description": "Draft. The initial HOS event catalogue: fifteen immutable fact types in five families, on the HOS Events envelope profile. Data objects are closed so that personal or commercial data cannot travel unnoticed. Snapshot mode is allowed for unit.status_changed only.",
    "allOf": [
      {
        "$ref": "urn:hos:schema:0.1:event-envelope"
      },
      {
        "properties": {
          "type": {
            "enum": [
              "reservation.created",
              "reservation.updated",
              "reservation.cancelled",
              "stay.expected",
              "stay.checked_in",
              "stay.check_in_reverted",
              "stay.checked_out",
              "stay.unit_assigned",
              "stay.unit_unassigned",
              "unit.status_changed",
              "unit.maintenance_scheduled",
              "unit.maintenance_cancelled",
              "housekeeping.task.created",
              "housekeeping.task.completed",
              "guest.message.received"
            ]
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "reservation.created"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/reservation.created"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "reservation.updated"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/reservation.updated"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "reservation.cancelled"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/reservation.cancelled"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.expected"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.expected"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.checked_in"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.checked_in"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.check_in_reverted"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.check_in_reverted"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.checked_out"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.checked_out"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.unit_assigned"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.unit_assigned"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.unit_unassigned"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.unit_unassigned"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "unit.status_changed"
            }
          }
        },
        "then": {
          "if": {
            "required": [
              "hosdatamode"
            ],
            "properties": {
              "hosdatamode": {
                "const": "snapshot"
              }
            }
          },
          "then": {
            "properties": {
              "data": {
                "$ref": "#/$defs/unit.status_changed.snapshot"
              }
            }
          },
          "else": {
            "properties": {
              "data": {
                "$ref": "#/$defs/unit.status_changed"
              }
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "unit.maintenance_scheduled"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/unit.maintenance_scheduled"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "unit.maintenance_cancelled"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/unit.maintenance_cancelled"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "housekeeping.task.created"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/housekeeping.task.created"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "housekeeping.task.completed"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/housekeeping.task.completed"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "guest.message.received"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/guest.message.received"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "not": {
                "const": "unit.status_changed"
              }
            }
          }
        },
        "then": {
          "not": {
            "required": [
              "hosdatamode"
            ],
            "properties": {
              "hosdatamode": {
                "const": "snapshot"
              }
            }
          }
        }
      }
    ],
    "$defs": {
      "reservation.created": {
        "title": "reservation.created",
        "description": "A reservation was created.",
        "x-hos-family": "Reservation",
        "x-hos-authority": "Reservation system (PMS)",
        "type": "object",
        "required": [
          "reservation_id",
          "status",
          "planned_arrival_date",
          "planned_departure_date"
        ],
        "properties": {
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "status": {
            "enum": [
              "tentative",
              "confirmed"
            ]
          },
          "planned_arrival_date": {
            "type": "string",
            "format": "date"
          },
          "planned_departure_date": {
            "type": "string",
            "format": "date"
          },
          "guest_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details."
          },
          "external_refs": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/externalRefs"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "reservation.updated": {
        "title": "reservation.updated",
        "description": "A reservation changed. changed_fields lists what changed; only those fields are carried, with their new values.",
        "x-hos-family": "Reservation",
        "x-hos-authority": "Reservation system (PMS)",
        "type": "object",
        "required": [
          "reservation_id",
          "changed_fields"
        ],
        "properties": {
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "changed_fields": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "enum": [
                "status",
                "planned_arrival_date",
                "planned_departure_date",
                "guest_id",
                "external_refs"
              ]
            }
          },
          "status": {
            "enum": [
              "tentative",
              "confirmed",
              "no_show"
            ]
          },
          "planned_arrival_date": {
            "type": "string",
            "format": "date"
          },
          "planned_departure_date": {
            "type": "string",
            "format": "date"
          },
          "guest_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details."
          },
          "external_refs": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/externalRefs"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false,
        "allOf": [
          {
            "if": {
              "properties": {
                "changed_fields": {
                  "contains": {
                    "const": "status"
                  }
                }
              }
            },
            "then": {
              "required": [
                "status"
              ]
            }
          },
          {
            "if": {
              "properties": {
                "changed_fields": {
                  "contains": {
                    "const": "planned_arrival_date"
                  }
                }
              }
            },
            "then": {
              "required": [
                "planned_arrival_date"
              ]
            }
          },
          {
            "if": {
              "properties": {
                "changed_fields": {
                  "contains": {
                    "const": "planned_departure_date"
                  }
                }
              }
            },
            "then": {
              "required": [
                "planned_departure_date"
              ]
            }
          },
          {
            "if": {
              "properties": {
                "changed_fields": {
                  "contains": {
                    "const": "guest_id"
                  }
                }
              }
            },
            "then": {
              "required": [
                "guest_id"
              ]
            }
          },
          {
            "if": {
              "properties": {
                "changed_fields": {
                  "contains": {
                    "const": "external_refs"
                  }
                }
              }
            },
            "then": {
              "required": [
                "external_refs"
              ]
            }
          }
        ]
      },
      "reservation.cancelled": {
        "title": "reservation.cancelled",
        "description": "A reservation was cancelled.",
        "x-hos-family": "Reservation",
        "x-hos-authority": "Reservation system (PMS)",
        "type": "object",
        "required": [
          "reservation_id"
        ],
        "properties": {
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "reason": {
            "enum": [
              "guest_request",
              "property_request",
              "payment_issue",
              "other"
            ]
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.expected": {
        "title": "stay.expected",
        "description": "A stay is expected: the operational visit that fulfils a reservation, one per booked unit. It is published as soon as the stay is committed, however early, and again whenever its planned times change; the latest occurrence wins. hosbusinessdate is the business date of the planned arrival. Unit assignment is a separate fact.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "reservation_id",
          "planned_arrival_at",
          "planned_departure_at"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "guest_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details."
          },
          "planned_arrival_at": {
            "type": "string",
            "format": "date-time",
            "description": "Planned check-in time. When the source plans stays in days, the arrival date at the Property's standard check-in time."
          },
          "planned_departure_at": {
            "type": "string",
            "format": "date-time",
            "description": "Planned check-out time. When the source plans stays in days, the departure date at the Property's standard check-out time."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.checked_in": {
        "title": "stay.checked_in",
        "description": "The guest checked in. time is the actual arrival.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "unit_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.check_in_reverted": {
        "title": "stay.check_in_reverted",
        "description": "A check-in was reverted, for example because it was recorded in error. The stay is expected again; time is when the check-in was reverted.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The unit of the reverted check-in, when known."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.checked_out": {
        "title": "stay.checked_out",
        "description": "The guest checked out. time is the actual departure.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "unit_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.unit_assigned": {
        "title": "stay.unit_assigned",
        "description": "A unit was assigned to a stay. Successive assignments, and the releases stay.unit_unassigned records, form the stay's assignment history.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "unit_id",
          "previous_unit_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "previous_unit_id": {
            "oneOf": [
              {
                "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
              },
              {
                "type": "null"
              }
            ]
          },
          "reason": {
            "enum": [
              "initial_assignment",
              "upgrade",
              "room_move",
              "readiness",
              "other"
            ]
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "stay.unit_unassigned": {
        "title": "stay.unit_unassigned",
        "description": "A unit was released from a stay, which has no unit until the next stay.unit_assigned. unit_id is the released unit; its entry in the assignment history ends at time.",
        "x-hos-family": "Stay",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "unit_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The unit released."
          },
          "reason": {
            "enum": [
              "room_move",
              "readiness",
              "maintenance",
              "other"
            ]
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "unit.status_changed": {
        "title": "unit.status_changed",
        "description": "One dimension of a unit changed. The event states only that dimension, the previous value when known, the new value, the authority source and an optional reason; it never alters the other dimensions.",
        "x-hos-family": "Unit",
        "x-hos-authority": "Declared per dimension (housekeeping system, PMS, maintenance)",
        "type": "object",
        "required": [
          "unit_id",
          "dimension",
          "current",
          "authority_source"
        ],
        "properties": {
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "dimension": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatusDimension"
          },
          "previous": {
            "type": "string"
          },
          "current": {
            "type": "string"
          },
          "authority_source": {
            "type": "string",
            "format": "uri",
            "description": "System of record for this value, as asserted by the producer. Informative: the manifests decide what HOS treats as authoritative."
          },
          "reason": {
            "enum": [
              "departure",
              "arrival",
              "cleaning_completed",
              "inspection",
              "maintenance",
              "commercial_decision",
              "manual_override",
              "other"
            ]
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false,
        "allOf": [
          {
            "if": {
              "properties": {
                "dimension": {
                  "const": "occupancy"
                }
              },
              "required": [
                "dimension"
              ]
            },
            "then": {
              "properties": {
                "previous": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/occupancyStatus"
                },
                "current": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/occupancyStatus"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "dimension": {
                  "const": "housekeeping"
                }
              },
              "required": [
                "dimension"
              ]
            },
            "then": {
              "properties": {
                "previous": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/housekeepingStatus"
                },
                "current": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/housekeepingStatus"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "dimension": {
                  "const": "maintenance"
                }
              },
              "required": [
                "dimension"
              ]
            },
            "then": {
              "properties": {
                "previous": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceStatus"
                },
                "current": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceStatus"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "dimension": {
                  "const": "commercial"
                }
              },
              "required": [
                "dimension"
              ]
            },
            "then": {
              "properties": {
                "previous": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/commercialStatus"
                },
                "current": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/commercialStatus"
                }
              }
            }
          }
        ]
      },
      "unit.status_changed.snapshot": {
        "title": "unit.status_changed (snapshot)",
        "description": "Snapshot mode, only with hosdatamode = snapshot and when the producer declares snapshots: the current value of each dimension the producer reports, sent when deltas cannot recover the state, for example after an outage.",
        "x-hos-family": "Unit",
        "x-hos-authority": "Declared per dimension",
        "type": "object",
        "required": [
          "unit_id",
          "statuses",
          "authority_source",
          "reason"
        ],
        "properties": {
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "statuses": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatuses"
          },
          "authority_source": {
            "type": "string",
            "format": "uri"
          },
          "reason": {
            "enum": [
              "recovery",
              "resynchronisation",
              "initial_load"
            ]
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "unit.maintenance_scheduled": {
        "title": "unit.maintenance_scheduled",
        "description": "A maintenance window was planned for a unit, or its plan changed. It is published again whenever the window changes; the latest occurrence for a maintenance_id wins. It does not change the unit's current statuses: unit.status_changed does, when the window begins.",
        "x-hos-family": "Unit",
        "x-hos-authority": "Declared: maintenance system or PMS",
        "type": "object",
        "required": [
          "maintenance_id",
          "unit_id",
          "starts_at",
          "ends_at",
          "statuses"
        ],
        "properties": {
          "maintenance_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "starts_at": {
            "type": "string",
            "format": "date-time",
            "description": "Start of the window. When the source plans windows in days, the window holds the unit as a stay would: its first day at the Property's standard check-in time."
          },
          "ends_at": {
            "type": "string",
            "format": "date-time",
            "description": "End of the window, exclusive. When the source plans windows in days, the day that frees the unit at the Property's standard check-out time."
          },
          "statuses": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceWindowStatuses"
          },
          "reason": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceReason"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "unit.maintenance_cancelled": {
        "title": "unit.maintenance_cancelled",
        "description": "A maintenance window was withdrawn. A window that ends as planned needs no event; one cut short is published again with its new end.",
        "x-hos-family": "Unit",
        "x-hos-authority": "Declared: maintenance system or PMS",
        "type": "object",
        "required": [
          "maintenance_id",
          "unit_id"
        ],
        "properties": {
          "maintenance_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "housekeeping.task.created": {
        "title": "housekeeping.task.created",
        "description": "A housekeeping task was created for a unit or a stay.",
        "x-hos-family": "Housekeeping",
        "x-hos-authority": "Housekeeping system",
        "type": "object",
        "required": [
          "task_id",
          "task_type",
          "priority"
        ],
        "properties": {
          "task_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "task_type": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskType"
          },
          "priority": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskPriority"
          },
          "due_at": {
            "type": "string",
            "format": "date-time"
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "unit_id"
            ]
          },
          {
            "required": [
              "stay_id"
            ]
          }
        ]
      },
      "housekeeping.task.completed": {
        "title": "housekeeping.task.completed",
        "description": "A housekeeping task was reported complete. Completing a task does not change a unit status by itself.",
        "x-hos-family": "Housekeeping",
        "x-hos-authority": "Housekeeping system",
        "type": "object",
        "required": [
          "task_id",
          "task_type"
        ],
        "properties": {
          "task_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "task_type": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskType"
          },
          "completed_by_ref": {
            "type": "string",
            "minLength": 1,
            "description": "Pseudonymous staff reference."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "unit_id"
            ]
          },
          {
            "required": [
              "stay_id"
            ]
          }
        ]
      },
      "guest.message.received": {
        "title": "guest.message.received",
        "description": "An inbound guest message was received. Only metadata and extracted signals travel; the content stays in the messaging system.",
        "x-hos-family": "Guest communication",
        "x-hos-authority": "Guest messaging system",
        "type": "object",
        "required": [
          "message_id",
          "channel",
          "sensitivity"
        ],
        "properties": {
          "message_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "channel": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/messageChannel"
          },
          "guest_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details."
          },
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "sensitivity": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/sensitivityClass",
            "description": "Sensitivity class of the original message content."
          },
          "signals": {
            "type": "array",
            "description": "Operational signals extracted from the message.",
            "items": {
              "type": "object",
              "required": [
                "kind",
                "expected_arrival_at"
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "early_arrival",
                    "late_arrival"
                  ]
                },
                "expected_arrival_at": {
                  "type": "string",
                  "format": "date-time"
                },
                "confidence": {
                  "type": "number",
                  "minimum": 0,
                  "maximum": 1,
                  "description": "Confidence of the extraction, when the signal was inferred from free text."
                }
              },
              "additionalProperties": false
            }
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "producer-manifest": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.1:producer-manifest",
    "title": "HOS 0.1 Event Producer manifest",
    "description": "Draft. A producer's versioned statement of exactly what it produces and authoritatively controls: events, dimensions, authority, snapshot support, delivery, replay, retention and known limitations. Public systems publish it at /.well-known/hos/manifest.json; private systems may use a configured authenticated URL. At most one producer may be authoritative for a given event type and dimension at a property. Signing (JWS with a published key, expiry and rotation) is still in progress; the signature member is reserved.",
    "type": "object",
    "required": [
      "hosmanifestversion",
      "producer",
      "name",
      "organization",
      "system_role",
      "property_ids",
      "events",
      "delivery",
      "replay",
      "retention",
      "limitations"
    ],
    "properties": {
      "hosmanifestversion": {
        "const": "0.1"
      },
      "producer": {
        "type": "string",
        "format": "uri",
        "description": "Must equal the source attribute of every event the producer emits."
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "organization": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": false
      },
      "system_role": {
        "enum": [
          "pms",
          "housekeeping",
          "maintenance",
          "messaging",
          "integration",
          "other"
        ]
      },
      "property_ids": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
        }
      },
      "entities": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "enum": [
            "Tenant",
            "Property",
            "Unit",
            "MaintenanceWindow",
            "Reservation",
            "Stay",
            "Task",
            "Guest",
            "Message"
          ]
        },
        "description": "Core entities the producer exposes."
      },
      "events": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": [
            "type",
            "authoritative"
          ],
          "properties": {
            "type": {
              "enum": [
                "reservation.created",
                "reservation.updated",
                "reservation.cancelled",
                "stay.expected",
                "stay.checked_in",
                "stay.check_in_reverted",
                "stay.checked_out",
                "stay.unit_assigned",
                "stay.unit_unassigned",
                "unit.status_changed",
                "unit.maintenance_scheduled",
                "unit.maintenance_cancelled",
                "housekeeping.task.created",
                "housekeeping.task.completed",
                "guest.message.received"
              ]
            },
            "dimensions": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatusDimension"
              },
              "description": "For unit.status_changed: the dimensions this declaration covers."
            },
            "authoritative": {
              "type": "boolean",
              "description": "true when this producer is the system of record for the event type (and dimensions) at the declared properties. Non-authoritative facts are recorded and shown, never merged into the authoritative value."
            },
            "snapshot": {
              "type": "boolean",
              "description": "true when the producer may send this type in snapshot mode. Snapshots from a producer that does not declare them are ignored."
            },
            "note": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "delivery": {
        "type": "object",
        "required": [
          "mechanisms",
          "guarantee",
          "ordering"
        ],
        "properties": {
          "mechanisms": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "enum": [
                "webhook",
                "polling",
                "stream",
                "file"
              ]
            }
          },
          "guarantee": {
            "const": "at-least-once",
            "description": "HOS delivery is at-least-once; consumers deduplicate on source and id."
          },
          "ordering": {
            "enum": [
              "none",
              "per-subject",
              "total"
            ],
            "description": "Ordering is never global; it holds only as declared here."
          }
        },
        "additionalProperties": false
      },
      "replay": {
        "type": "object",
        "required": [
          "supported"
        ],
        "properties": {
          "supported": {
            "type": "boolean"
          },
          "window_days": {
            "type": "integer",
            "minimum": 0,
            "description": "A certified Event Producer profile provides at least 30 days."
          },
          "format": {
            "const": "jsonl",
            "description": "Replays are JSON Lines: one event per line, in delivery order."
          }
        },
        "additionalProperties": false
      },
      "retention": {
        "type": "object",
        "required": [
          "event_days"
        ],
        "properties": {
          "event_days": {
            "type": "integer",
            "minimum": 0
          }
        },
        "additionalProperties": false
      },
      "limitations": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "description": "Known gaps, unsupported states and access constraints, stated explicitly. Empty only when there are none."
      },
      "signature": {
        "type": "object",
        "description": "Reserved. Manifest signing is in progress and not part of 0.1."
      }
    },
    "additionalProperties": false
  },
  "reference/arrival-readiness": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.1:reference:arrival-readiness",
    "title": "Arrival-readiness reference situations",
    "description": "Non-normative. Situations produced by the reference arrival-readiness projection. They use the HOS Events envelope so they can be replayed and audited, but they are not part of the HOS Events 0.1 catalogue and may change without a HIP.",
    "allOf": [
      {
        "$ref": "urn:hos:schema:0.1:event-envelope"
      },
      {
        "properties": {
          "type": {
            "enum": [
              "arrival.room_readiness_at_risk",
              "arrival.room_readiness_resolved"
            ]
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "arrival.room_readiness_at_risk"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/arrival.room_readiness_at_risk"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "arrival.room_readiness_resolved"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/arrival.room_readiness_resolved"
            }
          }
        }
      }
    ],
    "$defs": {
      "factRef": {
        "type": "object",
        "required": [
          "value",
          "source",
          "event_id",
          "time"
        ],
        "properties": {
          "value": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "format": "uri"
          },
          "event_id": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false,
        "description": "A value together with the fact it comes from."
      },
      "conflictRef": {
        "type": "object",
        "description": "A non-authoritative value that disagrees with the authoritative value and is not older than it.",
        "required": [
          "dimension",
          "value",
          "source",
          "event_id",
          "time"
        ],
        "properties": {
          "dimension": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatusDimension"
          },
          "value": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "format": "uri"
          },
          "event_id": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "eventRef": {
        "type": "object",
        "required": [
          "source",
          "id"
        ],
        "properties": {
          "source": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "maintenanceRef": {
        "type": "object",
        "description": "A maintenance window that blocks the unit when the guest is expected, and the fact it comes from.",
        "required": [
          "maintenance_id",
          "starts_at",
          "ends_at",
          "statuses",
          "source",
          "event_id",
          "time"
        ],
        "properties": {
          "maintenance_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "starts_at": {
            "type": "string",
            "format": "date-time"
          },
          "ends_at": {
            "type": "string",
            "format": "date-time"
          },
          "statuses": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceWindowStatuses"
          },
          "source": {
            "type": "string",
            "format": "uri"
          },
          "event_id": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "occupantRef": {
        "type": "object",
        "description": "Another stay still in house in the assigned unit: checked in, not checked out. planned_departure_at is its latest planned check-out, when known; source, event_id and time identify its check-in.",
        "required": [
          "stay_id",
          "planned_departure_at",
          "source",
          "event_id",
          "time"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "planned_departure_at": {
            "oneOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ]
          },
          "source": {
            "type": "string",
            "format": "uri"
          },
          "event_id": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "taskRef": {
        "type": "object",
        "required": [
          "task_id",
          "task_type",
          "status",
          "source",
          "event_id",
          "time"
        ],
        "properties": {
          "task_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "task_type": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskType"
          },
          "status": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskStatus"
          },
          "source": {
            "type": "string",
            "format": "uri"
          },
          "event_id": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "arrival.room_readiness_at_risk": {
        "title": "arrival.room_readiness_at_risk",
        "description": "The assigned unit may not be ready when the guest comes: the guest is expected before the planned check-in time and the unit is not ready, a maintenance window blocks the unit when the guest is expected, or another guest in house in the unit is not due to leave before then. A unit is not ready when its authoritative housekeeping status is not ready or unknown, a window blocks it, or another guest still holds it. expected_arrival_at is the latest arrival signal, or the planned check-in without one. Observation only.",
        "type": "object",
        "required": [
          "stay_id",
          "reservation_id",
          "unit_id",
          "planned_arrival_at",
          "expected_arrival_at",
          "housekeeping",
          "conflicts",
          "latest_task",
          "evidence"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "oneOf": [
              {
                "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
              },
              {
                "type": "null"
              }
            ]
          },
          "planned_arrival_at": {
            "type": "string",
            "format": "date-time"
          },
          "expected_arrival_at": {
            "type": "string",
            "format": "date-time"
          },
          "housekeeping": {
            "oneOf": [
              {
                "$ref": "#/$defs/factRef"
              },
              {
                "type": "null"
              }
            ]
          },
          "conflicts": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/conflictRef"
            }
          },
          "latest_task": {
            "oneOf": [
              {
                "$ref": "#/$defs/taskRef"
              },
              {
                "type": "null"
              }
            ]
          },
          "maintenance": {
            "$ref": "#/$defs/maintenanceRef"
          },
          "occupied_by": {
            "$ref": "#/$defs/occupantRef"
          },
          "evidence": {
            "type": "array",
            "description": "Facts the situation is derived from, sorted by occurrence time, then source, then id.",
            "items": {
              "$ref": "#/$defs/eventRef"
            }
          }
        },
        "additionalProperties": false
      },
      "arrival.room_readiness_resolved": {
        "title": "arrival.room_readiness_resolved",
        "description": "A previously raised room-readiness risk no longer applies.",
        "type": "object",
        "required": [
          "stay_id",
          "reservation_id",
          "unit_id",
          "reason",
          "planned_arrival_at",
          "expected_arrival_at",
          "housekeeping",
          "evidence"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "reservation_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "oneOf": [
              {
                "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
              },
              {
                "type": "null"
              }
            ]
          },
          "reason": {
            "enum": [
              "unit_ready",
              "unit_available",
              "unit_reassigned",
              "unit_vacated",
              "departure_before_arrival",
              "arrival_not_early",
              "reservation_inactive",
              "stay_started"
            ],
            "description": "What stopped the risk: the stay was given another unit, the unit became ready, its maintenance window went, the guest in house left or is now due to leave first, the arrival is no longer early, the reservation became inactive, or the stay started."
          },
          "planned_arrival_at": {
            "type": "string",
            "format": "date-time"
          },
          "expected_arrival_at": {
            "oneOf": [
              {
                "type": "string",
                "format": "date-time"
              },
              {
                "type": "null"
              }
            ]
          },
          "housekeeping": {
            "oneOf": [
              {
                "$ref": "#/$defs/factRef"
              },
              {
                "type": "null"
              }
            ]
          },
          "evidence": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/eventRef"
            }
          }
        },
        "additionalProperties": false
      }
    }
  }
};
