// Generated by scripts/generate.ts from public/spec/0.1/schemas. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

/** Opaque, stable HOS identifier, unique within its Tenant. It carries no business meaning and no personal data. */
export type HosId = string;

/** IANA time zone name, for example Europe/Paris. */
export type IanaTimezone = string;

/** ISO 3166-1 alpha-2 country code. */
export type CountryCode = string;

/** Local wall-clock time, HH:MM. */
export type LocalTime = string;

/** A typed, sourced reference to an identifier held by another system. */
export type ExternalRef = {
  /** URI of the system that issued the identifier. */
  source_system: string;
  /** Kind of identifier in that system, for example confirmation_number. */
  id_type: string;
  /** The identifier as issued by the source system. */
  source_id: string;
  /** verified when the identifier was confirmed with the source system; asserted when it is only reported. Omitted when not known. */
  verification?: "verified" | "asserted";
};

export type ExternalRefs = ExternalRef[];

/** Vendor detail under an inverted domain namespace such as com.example. Each namespace publishes its own schema and documentation, and can never redefine a Core field or enum. */
export type Extensions = {
  [key: string]: Record<string, unknown>;
};

/** Handling class. public: no restriction; internal: operational data for authorised participants; confidential: commercial or pseudonymous personal data; restricted: data whose disclosure could harm a person, such as special-category data. */
export type SensitivityClass = "public" | "internal" | "confidential" | "restricted";

/** The four independent dimensions of a Unit's status. */
export type UnitStatusDimension = "occupancy" | "housekeeping" | "maintenance" | "commercial";

/** Physical occupancy state. */
export type OccupancyStatus = "vacant" | "occupied" | "unknown";

/** Readiness as reported by the housekeeping authority. */
export type HousekeepingStatus = "dirty" | "clean" | "inspected" | "unknown";

/** Basic operational availability; there is no detailed maintenance model in 0.1. */
export type MaintenanceStatus = "operational" | "out_of_service" | "unknown";

/** Commercial disposition as declared by the responsible system. */
export type CommercialStatus = "sellable" | "not_sellable" | "unknown";

/** Values of one or more Unit status dimensions. */
export type UnitStatuses = {
  occupancy?: OccupancyStatus;
  housekeeping?: HousekeepingStatus;
  maintenance?: MaintenanceStatus;
  commercial?: CommercialStatus;
};

/** The Unit statuses a maintenance window imposes while it lasts: maintenance out_of_service when the unit cannot be used, commercial not_sellable when it cannot be sold. */
export type MaintenanceWindowStatuses = {
  maintenance?: "out_of_service";
  commercial?: "not_sellable";
};

/** Why a maintenance window exists, when the source says. */
export type MaintenanceReason = "repair" | "renovation" | "internal_use" | "other";

/** Commercial status of a Reservation. */
export type ReservationStatus = "tentative" | "confirmed" | "cancelled" | "no_show";

/** Operational status of a Stay. */
export type StayStatus = "expected" | "in_house" | "departed" | "cancelled";

export type TaskType = "cleaning" | "inspection" | "turndown" | "maintenance" | "other";

export type TaskStatus = "open" | "in_progress" | "completed" | "cancelled";

export type TaskPriority = "low" | "normal" | "high" | "urgent";

export type MessageChannel = "sms" | "email" | "chat" | "messaging_app" | "ota_messaging" | "phone" | "other";

/** Security, policy and data-autonomy boundary. */
export type Tenant = {
  tenant_id: HosId;
};

/** Tenant, IANA time zone, country, business-date policy and standard check-in and check-out times. */
export type Property = {
  property_id: HosId;
  tenant_id: HosId;
  timezone: IanaTimezone;
  country: CountryCode;
  business_date_policy: {
    /** Local time at which the business date advances, for example 04:00 after night audit. */
    rollover_local_time: LocalTime;
  };
  /** Local time at which a stay starts when a source plans stays in days, for example 15:00. */
  standard_check_in_time?: LocalTime;
  /** Local time at which a stay ends when a source plans stays in days, for example 11:00. */
  standard_check_out_time?: LocalTime;
  external_refs?: ExternalRefs;
};

/** Property, local label or type, and four independent statuses. */
export type Unit = {
  unit_id: HosId;
  property_id: HosId;
  /** Local label, for example 204. */
  label?: string;
  /** Local type, for example double_room. */
  unit_type?: string;
  statuses: Required<UnitStatuses>;
  external_refs?: ExternalRefs;
};

/** A planned period when a Unit is out of service or cannot be sold: a repair, a renovation or internal use. Its statuses say which dimensions it affects. */
export type MaintenanceWindow = {
  maintenance_id: HosId;
  property_id: HosId;
  unit_id: HosId;
  /** Start of the window. When the source plans windows in days, the window holds the unit as a stay would: its first day at the Property's standard check-in time. */
  starts_at: string;
  /** End of the window, exclusive. When the source plans windows in days, the day that frees the unit at the Property's standard check-out time. */
  ends_at: string;
  statuses: MaintenanceWindowStatuses;
  reason?: MaintenanceReason;
  /** When the window was withdrawn, if it was. */
  cancelled_at?: string;
  external_refs?: ExternalRefs;
};

/** Property, commercial status, planned arrival and departure, and external references. */
export type Reservation = {
  reservation_id: HosId;
  property_id: HosId;
  status: ReservationStatus;
  planned_arrival_date: string;
  planned_departure_date: string;
  guest_id?: HosId;
  external_refs?: ExternalRefs;
};

/** Property, linked Reservation, planned and actual times, and Unit assignment history. A reservation for several units yields one Stay per unit. */
export type Stay = {
  stay_id: HosId;
  property_id: HosId;
  reservation_id: HosId;
  status: StayStatus;
  guest_id?: HosId;
  planned_arrival_at: string;
  planned_departure_at: string;
  actual_arrival_at?: string;
  actual_departure_at?: string;
  unit_assignments: Array<{
    unit_id: HosId;
    assigned_at: string;
    released_at?: string;
  }>;
};

/** Linked Property, Unit or Stay; type, status and priority. */
export type Task = {
  task_id: HosId;
  property_id: HosId;
  unit_id?: HosId;
  stay_id?: HosId;
  task_type: TaskType;
  status: TaskStatus;
  priority: TaskPriority;
};

/** Pseudonymous HOS identifiers and external references only. A producer without a stable guest identity publishes no guest_id, and never derives one from names or contact details. */
export type Guest = {
  guest_id: HosId;
  external_refs?: ExternalRefs;
};

/** Channel, direction, time, linked Guest or Stay, and sensitivity class. */
export type Message = {
  message_id: HosId;
  property_id: HosId;
  channel: MessageChannel;
  direction: "inbound" | "outbound";
  sent_at: string;
  guest_id?: HosId;
  stay_id?: HosId;
  sensitivity: SensitivityClass;
};

/** A traceable, reversible relationship created when two guest references are matched. Resolution is never destructive: records are linked, not merged. */
export type GuestIdentityLink = {
  link_id: HosId;
  guest_id: HosId;
  linked_to: {
    guest_id: HosId;
  } | {
    external_ref: ExternalRef;
  };
  /** System that proposed the match. */
  source: string;
  confidence: number;
  /** Pseudonymous reference of the person or process responsible for the link. */
  author: string;
  rationale: string;
  created_at: string;
  revoked_at?: string;
};

/** Draft. CloudEvents 1.0 in structured JSON mode with HOS extension attributes. Every HOS event, and every reference situation, uses this envelope. Attribute names follow CloudEvents rules: lower-case letters and digits, at most 20 characters, scalar values only. */
export type Envelope<TType extends string, TData> = {
  /** CloudEvents specification version. */
  specversion: "1.0";
  /** Producer-scoped, immutable event identity. With source, it is the duplicate key: a redelivered event keeps its id. */
  id: string;
  /** The producer. Must equal the producer declared in its Event Producer manifest. */
  source: string;
  /** Vendor-neutral HOS event type, named domain.resource.past_tense in the singular. */
  type: TType;
  /** When the fact occurred, when known. Otherwise the best time the producer has, qualified by hostimebasis. */
  time: string;
  /** HOS 0.1 data is always JSON. */
  datacontenttype: "application/json";
  /** Optional reference to the schema of data. */
  dataschema?: string;
  /** HOS version the event conforms to. */
  hosschemaversion: "0.1";
  /** When the HOS implementation (producer or adapter) recorded the event. HOS always carries it. */
  hosrecordedat: string;
  /** What time represents. Absent means occurred. modified means the source's last modification of the entity, when it does not date the change itself: the fact occurred at or before time. recorded means the occurrence time is unknown and time is when the producer or adapter recorded the fact. */
  hostimebasis?: "occurred" | "modified" | "recorded";
  /** Tenant: the security, policy and data-autonomy boundary. */
  hostenant: HosId;
  /** Property the fact belongs to: the operating context. */
  hosproperty: HosId;
  /** IANA time zone of the Property. Local times are derived from it, never assumed. */
  hospropertytimezone: IanaTimezone;
  /** Local operating (business) date the fact belongs to, when it matters. It can differ from the calendar date of time. */
  hosbusinessdate?: string;
  /** Typed HOS entity references implicated by the fact, as space-separated type:id pairs, for example stay:stay_1042 unit:unit_204. A string because CloudEvents attributes cannot hold arrays. */
  hossubjects: string;
  /** How to read data. Absent means delta. A snapshot must be declared here, be allowed for its type and be sensitivity-classified. */
  hosdatamode?: "delta" | "snapshot";
  /** Sensitivity class of data. Required for snapshots. */
  hossensitivity?: SensitivityClass;
  /** Source of the event that caused this one, when known. */
  hoscausationsource?: string;
  /** Id of the event that caused this one, when known. Used with hoscausationsource. */
  hoscausationid?: string;
  /** Who made the change in the producer, when it knows: user (a staff member), guest, system (the producer itself) or integration (another system through its API), with a pseudonymous, producer-scoped reference, for example user:staff_k3. Never a name or contact detail. */
  hosactor?: string;
  /** The normalized payload. Its shape is defined by type; vendor detail goes in data.extensions under an inverted domain namespace. */
  data: TData;
};

/** The data of reservation.created. */
export type ReservationCreatedData = {
  reservation_id: HosId;
  status: "tentative" | "confirmed";
  planned_arrival_date: string;
  planned_departure_date: string;
  /** Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details. */
  guest_id?: HosId;
  external_refs?: ExternalRefs;
  extensions?: Extensions;
};

/** A reservation was created. */
export type ReservationCreated = Envelope<"reservation.created", ReservationCreatedData>;

/** The data of reservation.updated. */
export type ReservationUpdatedData = {
  reservation_id: HosId;
  changed_fields: Array<"status" | "planned_arrival_date" | "planned_departure_date" | "guest_id" | "external_refs">;
  status?: "tentative" | "confirmed" | "no_show";
  planned_arrival_date?: string;
  planned_departure_date?: string;
  /** Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details. */
  guest_id?: HosId;
  external_refs?: ExternalRefs;
  extensions?: Extensions;
};

/** A reservation changed. changed_fields lists what changed; only those fields are carried, with their new values. */
export type ReservationUpdated = Envelope<"reservation.updated", ReservationUpdatedData>;

/** The data of reservation.cancelled. */
export type ReservationCancelledData = {
  reservation_id: HosId;
  reason?: "guest_request" | "property_request" | "payment_issue" | "other";
  extensions?: Extensions;
};

/** A reservation was cancelled. */
export type ReservationCancelled = Envelope<"reservation.cancelled", ReservationCancelledData>;

/** The data of stay.expected. */
export type StayExpectedData = {
  stay_id: HosId;
  reservation_id: HosId;
  /** Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details. */
  guest_id?: HosId;
  /** Planned check-in time. When the source plans stays in days, the arrival date at the Property's standard check-in time. */
  planned_arrival_at: string;
  /** Planned check-out time. When the source plans stays in days, the departure date at the Property's standard check-out time. */
  planned_departure_at: string;
  extensions?: Extensions;
};

/** A stay is expected: the operational visit that fulfils a reservation, one per booked unit. It is published as soon as the stay is committed, however early, and again whenever its planned times change; the latest occurrence wins. hosbusinessdate is the business date of the planned arrival. Unit assignment is a separate fact. */
export type StayExpected = Envelope<"stay.expected", StayExpectedData>;

/** The data of stay.checked_in. */
export type StayCheckedInData = {
  stay_id: HosId;
  unit_id: HosId;
  extensions?: Extensions;
};

/** The guest checked in. time is the actual arrival. */
export type StayCheckedIn = Envelope<"stay.checked_in", StayCheckedInData>;

/** The data of stay.check_in_reverted. */
export type StayCheckInRevertedData = {
  stay_id: HosId;
  /** The unit of the reverted check-in, when known. */
  unit_id?: HosId;
  extensions?: Extensions;
};

/** A check-in was reverted, for example because it was recorded in error. The stay is expected again; time is when the check-in was reverted. */
export type StayCheckInReverted = Envelope<"stay.check_in_reverted", StayCheckInRevertedData>;

/** The data of stay.checked_out. */
export type StayCheckedOutData = {
  stay_id: HosId;
  unit_id: HosId;
  extensions?: Extensions;
};

/** The guest checked out. time is the actual departure. */
export type StayCheckedOut = Envelope<"stay.checked_out", StayCheckedOutData>;

/** The data of stay.unit_assigned. */
export type StayUnitAssignedData = {
  stay_id: HosId;
  unit_id: HosId;
  previous_unit_id: HosId | null;
  reason?: "initial_assignment" | "upgrade" | "room_move" | "readiness" | "other";
  extensions?: Extensions;
};

/** A unit was assigned to a stay. Successive assignments, and the releases stay.unit_unassigned records, form the stay's assignment history. */
export type StayUnitAssigned = Envelope<"stay.unit_assigned", StayUnitAssignedData>;

/** The data of stay.unit_unassigned. */
export type StayUnitUnassignedData = {
  stay_id: HosId;
  /** The unit released. */
  unit_id: HosId;
  reason?: "room_move" | "readiness" | "maintenance" | "other";
  extensions?: Extensions;
};

/** A unit was released from a stay, which has no unit until the next stay.unit_assigned. unit_id is the released unit; its entry in the assignment history ends at time. */
export type StayUnitUnassigned = Envelope<"stay.unit_unassigned", StayUnitUnassignedData>;

/** One dimension of a unit changed. The event states only that dimension, the previous value when known, the new value, the authority source and an optional reason; it never alters the other dimensions. */
export type UnitStatusChangedData = {
  unit_id: HosId;
  dimension: UnitStatusDimension;
  previous?: string;
  current: string;
  /** System of record for this value, as asserted by the producer. Informative: the manifests decide what HOS treats as authoritative. */
  authority_source: string;
  reason?: "departure" | "arrival" | "cleaning_completed" | "inspection" | "maintenance" | "commercial_decision" | "manual_override" | "other";
  extensions?: Extensions;
};

/** Snapshot mode, only with hosdatamode = snapshot and when the producer declares snapshots: the current value of each dimension the producer reports, sent when deltas cannot recover the state, for example after an outage. */
export type UnitStatusChangedSnapshotData = {
  unit_id: HosId;
  statuses: UnitStatuses;
  authority_source: string;
  reason: "recovery" | "resynchronisation" | "initial_load";
  extensions?: Extensions;
};

/** One dimension of a unit changed. The event states only that dimension, the previous value when known, the new value, the authority source and an optional reason; it never alters the other dimensions. */
export type UnitStatusChanged = Envelope<"unit.status_changed", UnitStatusChangedData | UnitStatusChangedSnapshotData>;

/** The data of unit.maintenance_scheduled. */
export type UnitMaintenanceScheduledData = {
  maintenance_id: HosId;
  unit_id: HosId;
  /** Start of the window. When the source plans windows in days, the window holds the unit as a stay would: its first day at the Property's standard check-in time. */
  starts_at: string;
  /** End of the window, exclusive. When the source plans windows in days, the day that frees the unit at the Property's standard check-out time. */
  ends_at: string;
  statuses: MaintenanceWindowStatuses;
  reason?: MaintenanceReason;
  extensions?: Extensions;
};

/** A maintenance window was planned for a unit, or its plan changed. It is published again whenever the window changes; the latest occurrence for a maintenance_id wins. It does not change the unit's current statuses: unit.status_changed does, when the window begins. */
export type UnitMaintenanceScheduled = Envelope<"unit.maintenance_scheduled", UnitMaintenanceScheduledData>;

/** The data of unit.maintenance_cancelled. */
export type UnitMaintenanceCancelledData = {
  maintenance_id: HosId;
  unit_id: HosId;
  extensions?: Extensions;
};

/** A maintenance window was withdrawn. A window that ends as planned needs no event; one cut short is published again with its new end. */
export type UnitMaintenanceCancelled = Envelope<"unit.maintenance_cancelled", UnitMaintenanceCancelledData>;

/** The data of housekeeping.task.created. */
export type HousekeepingTaskCreatedData = {
  task_id: HosId;
  unit_id?: HosId;
  stay_id?: HosId;
  task_type: TaskType;
  priority: TaskPriority;
  due_at?: string;
  extensions?: Extensions;
};

/** A housekeeping task was created for a unit or a stay. */
export type HousekeepingTaskCreated = Envelope<"housekeeping.task.created", HousekeepingTaskCreatedData>;

/** The data of housekeeping.task.completed. */
export type HousekeepingTaskCompletedData = {
  task_id: HosId;
  unit_id?: HosId;
  stay_id?: HosId;
  task_type: TaskType;
  /** Pseudonymous staff reference. */
  completed_by_ref?: string;
  extensions?: Extensions;
};

/** A housekeeping task was reported complete. Completing a task does not change a unit status by itself. */
export type HousekeepingTaskCompleted = Envelope<"housekeeping.task.completed", HousekeepingTaskCompletedData>;

/** The data of guest.message.received. */
export type GuestMessageReceivedData = {
  message_id: HosId;
  channel: MessageChannel;
  /** Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details. */
  guest_id?: HosId;
  stay_id?: HosId;
  /** Sensitivity class of the original message content. */
  sensitivity: SensitivityClass;
  /** Operational signals extracted from the message. */
  signals?: Array<{
    kind: "early_arrival" | "late_arrival";
    expected_arrival_at: string;
    /** Confidence of the extraction, when the signal was inferred from free text. */
    confidence?: number;
  }>;
  extensions?: Extensions;
};

/** An inbound guest message was received. Only metadata and extracted signals travel; the content stays in the messaging system. */
export type GuestMessageReceived = Envelope<"guest.message.received", GuestMessageReceivedData>;

/** Every type of HOS Events 0.1. */
export type HosEventType =
  | "reservation.created"
  | "reservation.updated"
  | "reservation.cancelled"
  | "stay.expected"
  | "stay.checked_in"
  | "stay.check_in_reverted"
  | "stay.checked_out"
  | "stay.unit_assigned"
  | "stay.unit_unassigned"
  | "unit.status_changed"
  | "unit.maintenance_scheduled"
  | "unit.maintenance_cancelled"
  | "housekeeping.task.created"
  | "housekeeping.task.completed"
  | "guest.message.received";

/** Every event of HOS Events 0.1. */
export type HosFact =
  | ReservationCreated
  | ReservationUpdated
  | ReservationCancelled
  | StayExpected
  | StayCheckedIn
  | StayCheckInReverted
  | StayCheckedOut
  | StayUnitAssigned
  | StayUnitUnassigned
  | UnitStatusChanged
  | UnitMaintenanceScheduled
  | UnitMaintenanceCancelled
  | HousekeepingTaskCreated
  | HousekeepingTaskCompleted
  | GuestMessageReceived;

/** Draft. A producer's versioned statement of exactly what it produces and authoritatively controls: events, dimensions, authority, snapshot support, delivery, replay, retention and known limitations. Public systems publish it at /.well-known/hos/manifest.json; private systems may use a configured authenticated URL. At most one producer may be authoritative for a given event type and dimension at a property. The manifest carries no signature: its producer signs it with a detached JWS, published beside it at /.well-known/hos/manifest.jws, and publishes its keys at /.well-known/hos/jwks.json. */
export type ProducerManifest = {
  hosmanifestversion: "0.1";
  /** Must equal the source attribute of every event the producer emits. */
  producer: string;
  name: string;
  organization: {
    name: string;
    url?: string;
  };
  system_role: "pms" | "housekeeping" | "maintenance" | "messaging" | "integration" | "other";
  property_ids: HosId[];
  /** Core entities the producer exposes. */
  entities?: Array<"Tenant" | "Property" | "Unit" | "MaintenanceWindow" | "Reservation" | "Stay" | "Task" | "Guest" | "Message">;
  events: Array<{
    type: HosEventType;
    /** For unit.status_changed: the dimensions this declaration covers. */
    dimensions?: UnitStatusDimension[];
    /** true when this producer is the system of record for the event type (and dimensions) at the declared properties. Non-authoritative facts are recorded and shown, never merged into the authoritative value. */
    authoritative: boolean;
    /** true when the producer may send this type in snapshot mode. Snapshots from a producer that does not declare them are ignored. */
    snapshot?: boolean;
    note?: string;
  }>;
  delivery: {
    mechanisms: Array<"webhook" | "polling" | "stream" | "file">;
    /** HOS delivery is at-least-once; consumers deduplicate on source and id. */
    guarantee: "at-least-once";
    /** Ordering is never global; it holds only as declared here. */
    ordering: "none" | "per-subject" | "total";
  };
  replay: {
    supported: boolean;
    /** A certified Event Producer profile provides at least 30 days. */
    window_days?: number;
    /** Replays are JSON Lines: one event per line, in delivery order. */
    format?: "jsonl";
  };
  retention: {
    event_days: number;
  };
  /** Known gaps, unsupported states and access constraints, stated explicitly. Empty only when there are none. */
  limitations: string[];
};
