// Generated by scripts/generate.ts from public/spec/0.2/examples. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

// Each published HOS 0.2 example, typed as its command, approval, policy, manifest or event: the SDK's typecheck fails when an
// example no longer fits.

import type {
  Approval,
  CommandStatusChanged,
  GuestMessageSendCommand,
  GuestMessageSent,
  HousekeepingTaskReprioritizeCommand,
  HousekeepingTaskReprioritized,
  Policy,
  ProducerManifestV02,
  StayUnitAssignCommand,
} from "../src/index.ts";

export const examplesV02 = {
  "approval.json": {
    "hosapprovalversion": "0.2",
    "approval_id": "apr_55c1d0e9",
    "command_id": "cmd_7f3a91c2",
    "command_digest": "sha-256:f2fe580a85056adc14bf68409134801426517997d83e8f29f32438b115d983f9",
    "hostenant": "tenant_demo",
    "decision": "approved",
    "approver": "user:manager_a1",
    "approver_role": "front_office_manager",
    "decided_at": "2026-07-14T09:07:12Z",
    "expires_at": "2026-07-14T09:37:12Z",
    "policy": {
      "policy_id": "pol_front_office",
      "version": "2026-10-01"
    }
  } satisfies Approval,
  "command.status_changed.json": {
    "specversion": "1.0",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.2",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-14",
    "id": "gw-000042",
    "source": "urn:hos:gateway:demo",
    "type": "command.status_changed",
    "time": "2026-07-14T09:07:12Z",
    "hosrecordedat": "2026-07-14T09:07:12Z",
    "hossubjects": "command:cmd_7f3a91c2 stay:stay_1042",
    "hosactor": "user:manager_a1",
    "data": {
      "command_id": "cmd_7f3a91c2",
      "command_type": "stay.unit_assign",
      "previous_status": "pending_approval",
      "status": "approved",
      "approval_id": "apr_55c1d0e9",
      "command_digest": "sha-256:f2fe580a85056adc14bf68409134801426517997d83e8f29f32438b115d983f9"
    }
  } satisfies CommandStatusChanged,
  "commands/guest.message.send.json": {
    "hoscommandversion": "0.2",
    "command_id": "cmd_91c4e6d7",
    "type": "guest.message.send",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "target": "stay:stay_1042",
    "handler": "urn:hos:messaging:demo",
    "idempotency_key": "stay_1042-room-ready-notice",
    "requester": "integration:front_office_assistant",
    "requested_at": "2026-07-14T09:20:00Z",
    "expires_at": "2026-07-14T11:20:00Z",
    "evidence": [
      {
        "source": "urn:hos:pms:demo",
        "id": "pms-000412"
      }
    ],
    "policy": {
      "policy_id": "pol_front_office",
      "version": "2026-10-01"
    },
    "preconditions": [
      {
        "kind": "stay_status",
        "in": [
          "expected"
        ]
      },
      {
        "kind": "facts_fresh",
        "max_age_seconds": 600
      }
    ],
    "data": {
      "stay_id": "stay_1042",
      "channel": "sms",
      "template_id": "tpl_room_ready",
      "parameters": {
        "unit_label": "212"
      }
    }
  } satisfies GuestMessageSendCommand,
  "commands/housekeeping.task.reprioritize.json": {
    "hoscommandversion": "0.2",
    "command_id": "cmd_2b81d0a4",
    "type": "housekeeping.task.reprioritize",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "target": "task:task_5521",
    "handler": "urn:hos:housekeeping:demo",
    "idempotency_key": "task_5521-urgent-early-arrival",
    "requester": "user:staff_k3",
    "requested_at": "2026-07-14T09:10:00Z",
    "expires_at": "2026-07-14T10:10:00Z",
    "evidence": [
      {
        "source": "urn:hos:projection:arrival-readiness",
        "id": "sit_000187"
      }
    ],
    "policy": {
      "policy_id": "pol_front_office",
      "version": "2026-10-01"
    },
    "preconditions": [
      {
        "kind": "task_status",
        "in": [
          "open",
          "in_progress"
        ]
      },
      {
        "kind": "task_priority",
        "equals": "normal"
      },
      {
        "kind": "facts_fresh",
        "max_age_seconds": 600
      }
    ],
    "data": {
      "task_id": "task_5521",
      "priority": "urgent"
    }
  } satisfies HousekeepingTaskReprioritizeCommand,
  "commands/stay.unit_assign.json": {
    "hoscommandversion": "0.2",
    "command_id": "cmd_7f3a91c2",
    "type": "stay.unit_assign",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "handler": "urn:hos:pms:demo",
    "target": "stay:stay_1042",
    "idempotency_key": "stay_1042-unit_212-readiness",
    "requester": "user:staff_k3",
    "requested_at": "2026-07-14T09:05:00Z",
    "expires_at": "2026-07-14T10:05:00Z",
    "evidence": [
      {
        "source": "urn:hos:projection:arrival-readiness",
        "id": "sit_000187"
      }
    ],
    "policy": {
      "policy_id": "pol_front_office",
      "version": "2026-10-01"
    },
    "preconditions": [
      {
        "kind": "stay_status",
        "in": [
          "expected"
        ]
      },
      {
        "kind": "unit_assignment",
        "equals": "unit_204"
      },
      {
        "kind": "unit_status",
        "unit_id": "unit_212",
        "dimension": "housekeeping",
        "in": [
          "inspected"
        ]
      },
      {
        "kind": "unit_status",
        "unit_id": "unit_212",
        "dimension": "maintenance",
        "in": [
          "operational"
        ]
      },
      {
        "kind": "facts_fresh",
        "max_age_seconds": 600
      }
    ],
    "data": {
      "stay_id": "stay_1042",
      "unit_id": "unit_212",
      "reason": "readiness"
    }
  } satisfies StayUnitAssignCommand,
  "guest.message.sent.json": {
    "specversion": "1.0",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.2",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-14",
    "id": "msg-000208",
    "source": "urn:hos:messaging:demo",
    "type": "guest.message.sent",
    "time": "2026-07-14T09:21:40Z",
    "hosrecordedat": "2026-07-14T09:21:41Z",
    "hossubjects": "message:msg_7783 stay:stay_1042",
    "hosactor": "integration:hos_command_handler",
    "data": {
      "message_id": "msg_7783",
      "channel": "sms",
      "template_id": "tpl_room_ready",
      "stay_id": "stay_1042",
      "sensitivity": "confidential"
    }
  } satisfies GuestMessageSent,
  "housekeeping.task.reprioritized.json": {
    "specversion": "1.0",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.2",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-14",
    "id": "hk-000917",
    "source": "urn:hos:housekeeping:demo",
    "type": "housekeeping.task.reprioritized",
    "time": "2026-07-14T09:12:30Z",
    "hosrecordedat": "2026-07-14T09:12:31Z",
    "hossubjects": "task:task_5521 unit:unit_212",
    "hosactor": "integration:hos_command_handler",
    "data": {
      "task_id": "task_5521",
      "unit_id": "unit_212",
      "previous_priority": "normal",
      "priority": "urgent"
    }
  } satisfies HousekeepingTaskReprioritized,
  "policy.json": {
    "hospolicyversion": "0.2",
    "policy_id": "pol_front_office",
    "version": "2026-10-01",
    "tenant": "tenant_demo",
    "properties": [
      "prop_demo"
    ],
    "permissions": [
      {
        "type": "stay.unit_assign",
        "mode": "approve_and_run",
        "requesters": [
          "user:*",
          "integration:front_office_assistant"
        ],
        "approver_roles": [
          "front_office_manager"
        ],
        "allow_self_approval": false,
        "command_validity_seconds": 3600,
        "approval_validity_seconds": 1800,
        "required_preconditions": [
          "unit_status"
        ],
        "limits": {
          "max_per_hour": 20,
          "max_per_target_per_day": 3
        }
      },
      {
        "type": "housekeeping.task.reprioritize",
        "mode": "recommend",
        "requesters": [
          "user:*"
        ],
        "command_validity_seconds": 3600
      }
    ]
  } satisfies Policy,
  "producer-manifest.gateway.json": {
    "hosmanifestversion": "0.2",
    "producer": "urn:hos:gateway:demo",
    "name": "Synthetic command gateway",
    "organization": {
      "name": "HOS AI synthetic corpus"
    },
    "system_role": "integration",
    "property_ids": [
      "prop_demo"
    ],
    "events": [
      {
        "type": "command.status_changed",
        "statuses": [
          "proposed",
          "pending_approval",
          "approved",
          "rejected",
          "expired",
          "cancelled"
        ],
        "authoritative": true,
        "note": "The gateway publishes every transition up to approved, and the end of a command that is never sent."
      }
    ],
    "delivery": {
      "mechanisms": [
        "file"
      ],
      "guarantee": "at-least-once",
      "ordering": "per-subject"
    },
    "replay": {
      "supported": true,
      "window_days": 90,
      "format": "jsonl"
    },
    "retention": {
      "event_days": 90,
      "command_days": 90
    },
    "limitations": [
      "Approvers are authenticated by the gateway; approvals are not signed.",
      "The emergency stop of a tenant cancels the commands that have not been sent."
    ]
  } satisfies ProducerManifestV02,
  "producer-manifest.pms.json": {
    "hosmanifestversion": "0.2",
    "producer": "urn:hos:pms:demo",
    "name": "Synthetic PMS with commands",
    "organization": {
      "name": "HOS AI synthetic corpus"
    },
    "system_role": "pms",
    "property_ids": [
      "prop_demo"
    ],
    "entities": [
      "Reservation",
      "Stay",
      "Unit",
      "Guest"
    ],
    "events": [
      {
        "type": "reservation.created",
        "authoritative": true
      },
      {
        "type": "reservation.updated",
        "authoritative": true
      },
      {
        "type": "reservation.cancelled",
        "authoritative": true
      },
      {
        "type": "stay.expected",
        "authoritative": true
      },
      {
        "type": "stay.unit_assigned",
        "authoritative": true
      },
      {
        "type": "stay.checked_in",
        "authoritative": true
      },
      {
        "type": "stay.check_in_reverted",
        "authoritative": true
      },
      {
        "type": "stay.checked_out",
        "authoritative": true
      },
      {
        "type": "stay.unit_unassigned",
        "authoritative": true
      },
      {
        "type": "unit.maintenance_scheduled",
        "authoritative": true
      },
      {
        "type": "unit.maintenance_cancelled",
        "authoritative": true
      },
      {
        "type": "unit.status_changed",
        "dimensions": [
          "occupancy",
          "commercial"
        ],
        "authoritative": true
      },
      {
        "type": "unit.status_changed",
        "dimensions": [
          "housekeeping"
        ],
        "authoritative": false,
        "note": "The PMS mirrors housekeeping status; at this property the housekeeping system is the authority."
      },
      {
        "type": "command.status_changed",
        "statuses": [
          "executing",
          "succeeded",
          "failed"
        ],
        "authoritative": true,
        "note": "The handler publishes the transitions from the moment it sends the request."
      }
    ],
    "delivery": {
      "mechanisms": [
        "webhook"
      ],
      "guarantee": "at-least-once",
      "ordering": "per-subject"
    },
    "replay": {
      "supported": true,
      "window_days": 30,
      "format": "jsonl"
    },
    "retention": {
      "event_days": 90,
      "command_days": 90
    },
    "limitations": [
      "The PMS task module is not a declared source of housekeeping tasks at this property.",
      "Guest messages are not exposed.",
      "A stay.unit_assigned fact matches a command by its effect, so an identical change made by hand in the window confirms it too.",
      "Only stays that have not started can be assigned."
    ],
    "commands": [
      {
        "type": "stay.unit_assign",
        "authoritative": true,
        "targets": [
          "Stay"
        ],
        "preconditions": [
          "stay_status",
          "unit_assignment",
          "unit_status",
          "facts_fresh"
        ],
        "idempotency_window_seconds": 86400,
        "confirmation": {
          "events": [
            "stay.unit_assigned"
          ],
          "max_delay_seconds": 600,
          "attribution": "effect"
        },
        "limits": {
          "max_per_minute": 30
        },
        "note": "Assigns for the whole stay, without locking the unit. An assignment locked in the PMS is refused, never unlocked."
      }
    ]
  } satisfies ProducerManifestV02,
};
