// Generated by scripts/generate.ts from public/spec/0.1/examples. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

// Each published example, typed as its event or entity: the SDK's typecheck fails when an example no longer fits.

import type {
  GuestMessageReceived,
  HousekeepingTaskCompleted,
  HousekeepingTaskCreated,
  MaintenanceWindow,
  Property,
  ReservationCancelled,
  ReservationCreated,
  ReservationUpdated,
  StayCheckInReverted,
  StayCheckedIn,
  StayCheckedOut,
  StayExpected,
  StayUnitAssigned,
  StayUnitUnassigned,
  Unit,
  UnitMaintenanceCancelled,
  UnitMaintenanceScheduled,
  UnitStatusChanged,
} from "../src/index.ts";

export const examples = {
  "entities/maintenance-window.json": {
    "maintenance_id": "mnt_31",
    "property_id": "prop_demo",
    "unit_id": "unit_207",
    "starts_at": "2026-07-30T08:00:00Z",
    "ends_at": "2026-07-31T14:00:00Z",
    "statuses": {
      "maintenance": "out_of_service",
      "commercial": "not_sellable"
    },
    "reason": "repair"
  } satisfies MaintenanceWindow,
  "entities/property.json": {
    "property_id": "prop_demo",
    "tenant_id": "tenant_demo",
    "timezone": "Europe/Paris",
    "country": "FR",
    "business_date_policy": {
      "rollover_local_time": "04:00"
    },
    "standard_check_in_time": "15:00",
    "standard_check_out_time": "11:00",
    "external_refs": [
      {
        "source_system": "urn:hos:pms:demo",
        "id_type": "property_code",
        "source_id": "DEMO-PAR-01",
        "verification": "verified"
      }
    ]
  } satisfies Property,
  "entities/unit.json": {
    "unit_id": "unit_204",
    "property_id": "prop_demo",
    "label": "204",
    "unit_type": "double_room",
    "statuses": {
      "occupancy": "vacant",
      "housekeeping": "inspected",
      "maintenance": "operational",
      "commercial": "sellable"
    },
    "external_refs": [
      {
        "source_system": "urn:hos:pms:demo",
        "id_type": "room_number",
        "source_id": "204",
        "verification": "verified"
      }
    ]
  } satisfies Unit,
  "guest.message.received.json": {
    "specversion": "1.0",
    "id": "msg-000977",
    "source": "urn:hos:messaging:demo",
    "type": "guest.message.received",
    "time": "2026-07-30T09:40:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T09:40:04Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "message:msg_51_2 stay:stay_1042 guest:guest_7q2k",
    "data": {
      "message_id": "msg_51_2",
      "channel": "messaging_app",
      "guest_id": "guest_7q2k",
      "stay_id": "stay_1042",
      "sensitivity": "confidential",
      "signals": [
        {
          "kind": "early_arrival",
          "expected_arrival_at": "2026-07-30T10:30:00Z",
          "confidence": 0.92
        }
      ]
    }
  } satisfies GuestMessageReceived,
  "housekeeping.task.completed.json": {
    "specversion": "1.0",
    "id": "hk-002260",
    "source": "urn:hos:housekeeping:demo",
    "type": "housekeeping.task.completed",
    "time": "2026-07-30T08:20:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T08:20:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "task:task_88 unit:unit_204",
    "data": {
      "task_id": "task_88",
      "unit_id": "unit_204",
      "task_type": "cleaning",
      "completed_by_ref": "staff_k3"
    }
  } satisfies HousekeepingTaskCompleted,
  "housekeeping.task.created.json": {
    "specversion": "1.0",
    "id": "hk-002232",
    "source": "urn:hos:housekeeping:demo",
    "type": "housekeeping.task.created",
    "time": "2026-07-30T06:45:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T06:45:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "task:task_88 unit:unit_204",
    "hoscausationsource": "urn:hos:housekeeping:demo",
    "hoscausationid": "hk-002231",
    "data": {
      "task_id": "task_88",
      "unit_id": "unit_204",
      "task_type": "cleaning",
      "priority": "normal",
      "due_at": "2026-07-30T13:00:00Z"
    }
  } satisfies HousekeepingTaskCreated,
  "reservation.cancelled.json": {
    "specversion": "1.0",
    "id": "pms-000502",
    "source": "urn:hos:pms:demo",
    "type": "reservation.cancelled",
    "time": "2026-07-30T08:00:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T08:00:00.500Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "reservation:res_2211",
    "data": {
      "reservation_id": "res_2211",
      "reason": "guest_request"
    }
  } satisfies ReservationCancelled,
  "reservation.created.json": {
    "specversion": "1.0",
    "id": "pms-000312",
    "source": "urn:hos:pms:demo",
    "type": "reservation.created",
    "time": "2026-07-12T14:03:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-12T14:03:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-12",
    "hossubjects": "reservation:res_1042 guest:guest_7q2k",
    "data": {
      "reservation_id": "res_1042",
      "status": "confirmed",
      "planned_arrival_date": "2026-07-30",
      "planned_departure_date": "2026-08-01",
      "guest_id": "guest_7q2k",
      "external_refs": [
        {
          "source_system": "urn:hos:pms:demo",
          "id_type": "confirmation_number",
          "source_id": "DEMO-1042",
          "verification": "verified"
        }
      ]
    }
  } satisfies ReservationCreated,
  "reservation.updated.json": {
    "specversion": "1.0",
    "id": "pms-000501",
    "source": "urn:hos:pms:demo",
    "type": "reservation.updated",
    "time": "2026-07-30T08:00:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T08:00:00.500Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "reservation:res_2210",
    "data": {
      "reservation_id": "res_2210",
      "changed_fields": [
        "planned_departure_date"
      ],
      "planned_departure_date": "2026-08-03"
    }
  } satisfies ReservationUpdated,
  "stay.check_in_reverted.json": {
    "specversion": "1.0",
    "id": "pms-000482",
    "source": "urn:hos:pms:demo",
    "type": "stay.check_in_reverted",
    "time": "2026-07-30T11:02:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T11:02:01Z",
    "hosactor": "user:staff_d8",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_1044 unit:unit_211",
    "data": {
      "stay_id": "stay_1044",
      "unit_id": "unit_211"
    }
  } satisfies StayCheckInReverted,
  "stay.checked_in.json": {
    "specversion": "1.0",
    "id": "pms-000470",
    "source": "urn:hos:pms:demo",
    "type": "stay.checked_in",
    "time": "2026-07-30T10:35:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T10:35:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_1042 unit:unit_204",
    "data": {
      "stay_id": "stay_1042",
      "unit_id": "unit_204"
    }
  } satisfies StayCheckedIn,
  "stay.checked_out.json": {
    "specversion": "1.0",
    "id": "pms-000503",
    "source": "urn:hos:pms:demo",
    "type": "stay.checked_out",
    "time": "2026-07-30T08:47:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T08:47:00.500Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_0977 unit:unit_311",
    "data": {
      "stay_id": "stay_0977",
      "unit_id": "unit_311"
    }
  } satisfies StayCheckedOut,
  "stay.expected.json": {
    "specversion": "1.0",
    "id": "pms-000421",
    "source": "urn:hos:pms:demo",
    "type": "stay.expected",
    "time": "2026-07-30T06:05:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T06:05:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_1042 reservation:res_1042 guest:guest_7q2k",
    "data": {
      "stay_id": "stay_1042",
      "reservation_id": "res_1042",
      "guest_id": "guest_7q2k",
      "planned_arrival_at": "2026-07-30T13:00:00Z",
      "planned_departure_at": "2026-08-01T09:00:00Z"
    }
  } satisfies StayExpected,
  "stay.unit_assigned.json": {
    "specversion": "1.0",
    "id": "pms-000504",
    "source": "urn:hos:pms:demo",
    "type": "stay.unit_assigned",
    "time": "2026-07-30T08:00:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T08:00:00.500Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_1043 unit:unit_207",
    "data": {
      "stay_id": "stay_1043",
      "unit_id": "unit_207",
      "previous_unit_id": "unit_205",
      "reason": "room_move"
    }
  } satisfies StayUnitAssigned,
  "stay.unit_unassigned.json": {
    "specversion": "1.0",
    "id": "pms-000503",
    "source": "urn:hos:pms:demo",
    "type": "stay.unit_unassigned",
    "time": "2026-07-30T07:58:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T07:58:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "stay:stay_1043 unit:unit_205",
    "data": {
      "stay_id": "stay_1043",
      "unit_id": "unit_205",
      "reason": "room_move"
    }
  } satisfies StayUnitUnassigned,
  "unit.maintenance_cancelled.json": {
    "specversion": "1.0",
    "id": "pms-000398",
    "source": "urn:hos:pms:demo",
    "type": "unit.maintenance_cancelled",
    "time": "2026-07-28T16:40:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-28T16:40:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-28",
    "hossubjects": "unit:unit_207",
    "data": {
      "maintenance_id": "mnt_31",
      "unit_id": "unit_207"
    }
  } satisfies UnitMaintenanceCancelled,
  "unit.maintenance_scheduled.json": {
    "specversion": "1.0",
    "id": "pms-000391",
    "source": "urn:hos:pms:demo",
    "type": "unit.maintenance_scheduled",
    "time": "2026-07-28T09:12:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-28T09:12:01Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-28",
    "hossubjects": "unit:unit_207",
    "data": {
      "maintenance_id": "mnt_31",
      "unit_id": "unit_207",
      "starts_at": "2026-07-30T08:00:00Z",
      "ends_at": "2026-07-31T14:00:00Z",
      "statuses": {
        "maintenance": "out_of_service",
        "commercial": "not_sellable"
      },
      "reason": "repair"
    }
  } satisfies UnitMaintenanceScheduled,
  "unit.status_changed.json": {
    "specversion": "1.0",
    "id": "hk-002231",
    "source": "urn:hos:housekeeping:demo",
    "type": "unit.status_changed",
    "time": "2026-07-30T06:40:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T06:40:02Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "unit:unit_204",
    "data": {
      "unit_id": "unit_204",
      "dimension": "housekeeping",
      "previous": "inspected",
      "current": "dirty",
      "authority_source": "urn:hos:housekeeping:demo",
      "reason": "departure"
    }
  } satisfies UnitStatusChanged,
  "unit.status_changed.snapshot.json": {
    "specversion": "1.0",
    "id": "hk-002301",
    "source": "urn:hos:housekeeping:demo",
    "type": "unit.status_changed",
    "time": "2026-07-30T10:16:00Z",
    "datacontenttype": "application/json",
    "hosschemaversion": "0.1",
    "hosrecordedat": "2026-07-30T10:16:02Z",
    "hostenant": "tenant_demo",
    "hosproperty": "prop_demo",
    "hospropertytimezone": "Europe/Paris",
    "hosbusinessdate": "2026-07-30",
    "hossubjects": "unit:unit_204",
    "hosdatamode": "snapshot",
    "hossensitivity": "internal",
    "data": {
      "unit_id": "unit_204",
      "statuses": {
        "housekeeping": "inspected",
        "occupancy": "vacant"
      },
      "authority_source": "urn:hos:housekeeping:demo",
      "reason": "recovery"
    }
  } satisfies UnitStatusChanged,
};
