// Generated by scripts/generate.ts from public/spec/0.1/schemas. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

import type {
  Envelope,
  HosId,
  MaintenanceWindowStatuses,
  TaskStatus,
  TaskType,
  UnitStatusDimension,
} from "../types.generated.ts";

/** A value together with the fact it comes from. */
export type FactRef = {
  value: string;
  source: string;
  event_id: string;
  time: string;
};

/** A non-authoritative value that disagrees with the authoritative value and is not older than it. */
export type ConflictRef = {
  dimension: UnitStatusDimension;
  value: string;
  source: string;
  event_id: string;
  time: string;
};

export type EventRef = {
  source: string;
  id: string;
};

/** A maintenance window that blocks the unit when the guest is expected, and the fact it comes from. */
export type MaintenanceRef = {
  maintenance_id: HosId;
  starts_at: string;
  ends_at: string;
  statuses: MaintenanceWindowStatuses;
  source: string;
  event_id: string;
  time: string;
};

/** Another stay still in house in the assigned unit: checked in, not checked out. planned_departure_at is its latest planned check-out, when known; source, event_id and time identify its check-in. */
export type OccupantRef = {
  stay_id: HosId;
  planned_departure_at: string | null;
  source: string;
  event_id: string;
  time: string;
};

export type TaskRef = {
  task_id: HosId;
  task_type: TaskType;
  status: TaskStatus;
  source: string;
  event_id: string;
  time: string;
};

/** The data of arrival.room_readiness_at_risk. */
export type ArrivalRoomReadinessAtRiskData = {
  stay_id: HosId;
  reservation_id: HosId;
  unit_id: HosId | null;
  planned_arrival_at: string;
  expected_arrival_at: string;
  housekeeping: FactRef | null;
  conflicts: ConflictRef[];
  latest_task: TaskRef | null;
  maintenance?: MaintenanceRef;
  occupied_by?: OccupantRef;
  /** Facts the situation is derived from, sorted by occurrence time, then source, then id. */
  evidence: EventRef[];
};

/** The assigned unit may not be ready when the guest comes: the guest is expected before the planned check-in time and the unit is not ready, a maintenance window blocks the unit when the guest is expected, or another guest in house in the unit is not due to leave before then. A unit is not ready when its authoritative housekeeping status is not ready or unknown, a window blocks it, or another guest still holds it. expected_arrival_at is the latest arrival signal, or the planned check-in without one. Observation only. */
export type ArrivalRoomReadinessAtRisk = Envelope<"arrival.room_readiness_at_risk", ArrivalRoomReadinessAtRiskData>;

/** The data of arrival.room_readiness_resolved. */
export type ArrivalRoomReadinessResolvedData = {
  stay_id: HosId;
  reservation_id: HosId;
  unit_id: HosId | null;
  /** What stopped the risk: the stay was given another unit, the unit became ready, its maintenance window went, the guest in house left or is now due to leave first, the arrival is no longer early, the reservation became inactive, or the stay started. */
  reason: "unit_ready" | "unit_available" | "unit_reassigned" | "unit_vacated" | "departure_before_arrival" | "arrival_not_early" | "reservation_inactive" | "stay_started";
  planned_arrival_at: string;
  expected_arrival_at: string | null;
  housekeeping: FactRef | null;
  evidence: EventRef[];
};

/** A previously raised room-readiness risk no longer applies. */
export type ArrivalRoomReadinessResolved = Envelope<"arrival.room_readiness_resolved", ArrivalRoomReadinessResolvedData>;

/** Every type of Arrival-readiness reference situations. */
export type SituationType = "arrival.room_readiness_at_risk" | "arrival.room_readiness_resolved";

/** Every event of Arrival-readiness reference situations. */
export type Situation = ArrivalRoomReadinessAtRisk | ArrivalRoomReadinessResolved;
