import { readdirSync, readFileSync } from "node:fs";

// Generates the SDK files derived from the published HOS 0.1 artefacts in public/spec/0.1: the embedded schemas, the
// TypeScript types, and the examples typed as their events for the type tests. It handles only what the HOS schemas
// use: objects, enums, consts, references, oneOf, anyOf and allOf, arrays. Conditions (if/then, contains,
// dependentRequired), patterns and formats have no simple TypeScript equivalent and stay with validation.

type Schema = {
  $id?: string;
  $ref?: string;
  $defs?: Record<string, Schema>;
  title?: string;
  description?: string;
  type?: string | string[];
  const?: unknown;
  enum?: unknown[];
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  items?: Schema;
  oneOf?: Schema[];
  anyOf?: Schema[];
  allOf?: Schema[];
  if?: Schema;
  then?: Schema;
  else?: Schema;
};

type Output = { file: string; body: string; imports: Set<string> };
type Named = { name: string; schema: Schema; output: Output };

const spec = new URL("../../../public/spec/0.1/", import.meta.url);
const readJson = (file: string) => JSON.parse(readFileSync(new URL(file, spec), "utf8"));
const jsonFiles = (directory: string) =>
  readdirSync(new URL(directory, spec), { recursive: true })
    .map((file) => String(file).replaceAll("\\", "/"))
    .filter((file) => file.endsWith(".json"))
    .sort();

const header = (from: string) => `// Generated by scripts/generate.ts from public/spec/0.1/${from}. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.
`;

// reservation.created becomes ReservationCreated, hosId becomes HosId, maintenance-window becomes MaintenanceWindow.
const pascal = (key: string) =>
  key
    .split(/[._-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

// A definition named after an event type holds that event's data.
const definitionName = (key: string) => (key.includes(".") ? `${pascal(key)}Data` : pascal(key));

const doc = (description: string | undefined, indent: string) => (description ? `${indent}/** ${description.replaceAll("*/", "*\\/")} */\n` : "");
const literal = (value: unknown) => JSON.stringify(value);
const enumKey = (values: unknown[]) => literal([...values].sort());
const carriesType = (schema: Schema) => ["$ref", "const", "enum", "type", "oneOf", "anyOf", "allOf", "properties", "items"].some((keyword) => keyword in schema);

// The right-hand side of a type alias: on one line, or one member per line when long.
function union(members: string[]) {
  const line = members.join(" | ");
  return line.length <= 100 ? ` ${line}` : `\n${members.map((member) => `  | ${member}`).join("\n")}`;
}

function importList(names: Iterable<string>, from: string) {
  const sorted = [...names].sort();
  if (!sorted.length) return "";
  const line = `import type { ${sorted.join(", ")} } from "${from}";`;
  return `\n${line.length <= 120 ? line : `import type {\n${sorted.map((name) => `  ${name},\n`).join("")}} from "${from}";`}\n`;
}

// The event types of an event document, and the data definitions its if/then entries choose for a type.
const typesOf = (document: Schema) => document.allOf!.find((part) => part.properties?.type?.enum)!.properties!.type.enum as string[];
function dataKeys(document: Schema, type: string) {
  const keys: string[] = [];
  const walk = (part: Schema | undefined) => {
    if (!part) return;
    if (part.properties?.data?.$ref) keys.push(part.properties.data.$ref.replace("#/$defs/", ""));
    walk(part.then);
    walk(part.else);
  };
  for (const part of document.allOf!) if (part.if?.properties?.type?.const === type) walk(part.then);
  const order = Object.keys(document.$defs!);
  return keys.sort((a, b) => order.indexOf(a) - order.indexOf(b));
}

export function generate(): Record<string, string> {
  const documents = {
    core: readJson("schemas/core.schema.json") as Schema,
    envelope: readJson("schemas/event-envelope.schema.json") as Schema,
    events: readJson("schemas/events.schema.json") as Schema,
    manifest: readJson("schemas/producer-manifest.schema.json") as Schema,
    reference: readJson("schemas/reference/arrival-readiness.schema.json") as Schema,
  };
  const core: Output = { file: "src/types.generated.ts", body: "", imports: new Set() };
  const reference: Output = { file: "src/reference/types.generated.ts", body: "", imports: new Set() };

  // Every definition gets one name, in the output that holds its schema. Enums are also found by their values, so an
  // inline enum equal to a named one, such as the event types a manifest lists, uses its name.
  const named = new Map<string, Named>();
  const enums = new Map<string, Named>();
  const register = (document: Schema, output: Output) => {
    for (const [key, schema] of Object.entries(document.$defs ?? {})) {
      const definition = { name: definitionName(key), schema, output };
      named.set(`${document.$id}#/$defs/${key}`, definition);
      if (schema.enum) enums.set(enumKey(schema.enum), definition);
    }
  };
  register(documents.core, core);
  register(documents.events, core);
  register(documents.reference, reference);
  enums.set(enumKey(typesOf(documents.events)), { name: "HosEventType", schema: {}, output: core });

  function refer(definition: Named, output: Output) {
    if (definition.output !== output) output.imports.add(definition.name);
    return definition.name;
  }

  function resolve(ref: string, base: string) {
    const definition = named.get(ref.startsWith("#") ? `${base}${ref}` : ref);
    if (!definition) throw new Error(`Unknown reference ${ref} in ${base}`);
    return definition;
  }

  function expression(schema: Schema, base: string, output: Output, indent: string): string {
    if (schema.$ref) return refer(resolve(schema.$ref, base), output);
    if ("const" in schema) return literal(schema.const);
    if (schema.enum) {
      const shared = enums.get(enumKey(schema.enum));
      return shared ? refer(shared, output) : schema.enum.map(literal).join(" | ");
    }
    // Branches that only add constraints, such as anyOf of required lists or allOf of if/then, do not change the type.
    const branches = (schema.oneOf ?? schema.anyOf ?? []).filter(carriesType);
    if (branches.length) return branches.map((branch) => expression(branch, base, output, indent)).join(" | ");
    const parts = (schema.allOf ?? []).filter(carriesType);
    if (parts.length && !schema.type) {
      const type = parts.map((part) => expression(part, base, output, indent)).join(" & ");
      if (!schema.required) return type;
      // required next to a reference makes the referenced properties mandatory.
      const target = parts.length === 1 && parts[0].$ref ? resolve(parts[0].$ref, base).schema : undefined;
      const all = Object.keys(target?.properties ?? { "": 0 }).every((name) => schema.required!.includes(name));
      return all ? `Required<${type}>` : `${type} & Required<Pick<${type}, ${schema.required.map(literal).join(" | ")}>>`;
    }
    const types = [schema.type ?? []].flat();
    if (types.length > 1) return types.map((type) => expression({ ...schema, type }, base, output, indent)).join(" | ");
    switch (types[0]) {
      case "string":
        return "string";
      case "number":
      case "integer":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array": {
        const item = schema.items ? expression(schema.items, base, output, indent) : "unknown";
        return /[ |{<]/.test(item) ? `Array<${item}>` : `${item}[]`;
      }
      case "object":
        return object(schema, base, output, indent);
    }
    return "unknown";
  }

  function object(schema: Schema, base: string, output: Output, indent: string, replace: Record<string, string> = {}) {
    const properties = Object.entries(schema.properties ?? {});
    const extra = typeof schema.additionalProperties === "object" ? schema.additionalProperties : undefined;
    if (!properties.length && !extra) return "Record<string, unknown>";
    const inner = `${indent}  `;
    const lines = properties.map(([name, property]) => {
      const optional = schema.required?.includes(name) ? "" : "?";
      return `${doc(property.description, inner)}${inner}${name}${optional}: ${replace[name] ?? expression(property, base, output, inner)};\n`;
    });
    if (extra) lines.push(`${inner}[key: string]: ${expression(extra, base, output, inner)};\n`);
    return `{\n${lines.join("")}${indent}}`;
  }

  function definition(name: string, schema: Schema, base: string, output: Output, description = schema.description) {
    // A named enum is written out, never replaced by itself.
    const body = schema.enum ? union(schema.enum.map(literal)) : ` ${expression(schema, base, output, "")}`;
    output.body += `\n${doc(description, "")}export type ${name} =${body};\n`;
  }

  // An event document: helper definitions first, then for each type its data and its event on the envelope, then the
  // unions of the types and of the events.
  function eventDocument(document: Schema, output: Output, typeUnion: string, eventUnion: string) {
    const types = typesOf(document);
    const data = new Set(types.flatMap((type) => dataKeys(document, type)));
    for (const [key, schema] of Object.entries(document.$defs!)) if (!data.has(key)) definition(definitionName(key), schema, document.$id!, output);
    for (const type of types) {
      const keys = dataKeys(document, type);
      for (const key of keys) definition(definitionName(key), document.$defs![key], document.$id!, output, keys.length === 1 ? `The data of ${type}.` : undefined);
      const description = (document.$defs![type] ?? document.$defs![keys[0]]).description;
      output.body += `\n${doc(description, "")}export type ${pascal(type)} = Envelope<${literal(type)}, ${keys.map(definitionName).join(" | ")}>;\n`;
    }
    const title = document.title ?? document.$id;
    output.body += `\n${doc(`Every type of ${title}.`, "")}export type ${typeUnion} =${union(types.map(literal))};\n`;
    output.body += `\n${doc(`Every event of ${title}.`, "")}export type ${eventUnion} =${union(types.map(pascal))};\n`;
    refer({ name: "Envelope", schema: {}, output: core }, output);
  }

  for (const [key, schema] of Object.entries(documents.core.$defs!)) definition(definitionName(key), schema, documents.core.$id!, core);
  core.body += `\n${doc(documents.envelope.description, "")}export type Envelope<TType extends string, TData> = ${object(documents.envelope, documents.envelope.$id!, core, "", { type: "TType", data: "TData" })};\n`;
  eventDocument(documents.events, core, "HosEventType", "HosFact");
  definition("ProducerManifest", documents.manifest, documents.manifest.$id!, core);
  eventDocument(documents.reference, reference, "SituationType", "Situation");

  const schemas = Object.fromEntries(jsonFiles("schemas/").map((file) => [file.replace(/\.schema\.json$/, ""), readJson(`schemas/${file}`)]));
  // An event example is typed as its event, an entity example as the entity its file names.
  const examples = jsonFiles("examples/").map((file) => {
    const example = readJson(`examples/${file}`);
    return { file, example, type: pascal(example.type ?? file.replace(/^.*\//, "").replace(/\.json$/, "")) };
  });

  return {
    "src/schemas.generated.ts": `${header("schemas")}
import type { AnySchemaObject } from "ajv/dist/2020.js";

export const schemas: Record<string, AnySchemaObject> = ${JSON.stringify(schemas, null, 2)};
`,
    [core.file]: `${header("schemas")}${importList(core.imports, "")}${core.body}`,
    [reference.file]: `${header("schemas")}${importList(reference.imports, "../types.generated.ts")}${reference.body}`,
    "test/examples.generated.ts": `${header("examples")}
// Each published example, typed as its event or entity: the SDK's typecheck fails when an example no longer fits.
${importList(new Set(examples.map((item) => item.type)), "../src/index.ts")}
export const examples = {
${examples.map(({ file, example, type }) => `  ${literal(file)}: ${JSON.stringify(example, null, 2).replaceAll("\n", "\n  ")} satisfies ${type},\n`).join("")}};
`,
  };
}
