// Embeds the published HOS 0.1 JSON Schemas in the SDK, so validation reads no file and runs in a browser as well as in
// Node. public/spec/0.1/schemas stays the source of truth: after changing a schema, run this script again. A test fails
// until the embedded copy matches the published files.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const source = new URL("../../../public/spec/0.1/schemas/", import.meta.url);
const target = new URL("../src/schemas.generated.ts", import.meta.url);

const files = readdirSync(source, { recursive: true })
  .map((file) => file.replaceAll("\\", "/"))
  .filter((file) => file.endsWith(".schema.json"))
  .sort();
const schemas = Object.fromEntries(files.map((file) => [file.replace(/\.schema\.json$/, ""), JSON.parse(readFileSync(new URL(file, source), "utf8"))]));

writeFileSync(
  target,
  `// Generated by scripts/embed-schemas.mjs from public/spec/0.1/schemas. Do not edit: change the published schema and run
// npm run embed-schemas -w @hos-ai/sdk.

import type { AnySchemaObject } from "ajv/dist/2020.js";

export const schemas: Record<string, AnySchemaObject> = ${JSON.stringify(schemas, null, 2)};
`,
);
console.log(`Embedded ${files.length} schemas: ${files.join(", ")}`);
