// Generated by scripts/generate.ts from public/spec/0.1/conformance. Do not edit: change the published files and run
// npm run generate -w @hos-ai/cli.

import type { ConformanceScenario, ExpectedOutcome, HosFact, ProducerManifest } from "@hos-ai/sdk";

export type EmbeddedScenario = { scenario: ConformanceScenario; manifests: ProducerManifest[]; events: HosFact[]; expected: ExpectedOutcome };

export const scenarios: Record<string, EmbeddedScenario> = {
  "arrival-readiness": {
    "scenario": {
      "scenario": "arrival-readiness",
      "hosschemaversion": "0.1",
      "status": "draft",
      "title": "Early arrival, unit not ready",
      "summary": "Synthetic facts from a PMS, a housekeeping system and a guest messaging platform for one property. Replay events.jsonl in file order through an implementation and compare its dispositions, readiness and situations with expected.json. The situations are non-normative; the dispositions follow the HOS Events 0.1 processing rules.",
      "covers": [
        "Nominal early-arrival, dirty-unit scenario",
        "Duplicate event (source + id deduplication)",
        "Out-of-order event",
        "Conflicting source facts",
        "Snapshot recovery with explicit classification",
        "Missing capability (undeclared means denied)"
      ],
      "tenant": {
        "id": "tenant_demo"
      },
      "property": {
        "id": "prop_demo",
        "timezone": "Europe/Paris",
        "country": "FR"
      },
      "projection": {
        "ready_housekeeping_statuses": [
          "clean",
          "inspected"
        ]
      },
      "files": {
        "events": "events.jsonl",
        "expected": "expected.json",
        "producers": [
          "producers/pms.json",
          "producers/housekeeping.json",
          "producers/messaging.json"
        ]
      },
      "deliveries": [
        {
          "delivery": 1,
          "checks": "Reservation context",
          "note": "The PMS created reservation res_1042 on 12 July for an arrival today. The guest is a pseudonymous id; the PMS confirmation number travels as a typed external reference."
        },
        {
          "delivery": 2,
          "checks": "Stay context",
          "note": "The PMS expects stay_1042 today, with the standard check-in at 15:00."
        },
        {
          "delivery": 3,
          "checks": "Unit assignment",
          "note": "The PMS assigns unit 204. Assignment is a fact of its own, so the stay keeps an assignment history."
        },
        {
          "delivery": 4,
          "checks": "Authoritative status",
          "note": "The housekeeping system, the declared authority for housekeeping status, reports unit 204 dirty after the previous guest left. Only that dimension changes."
        },
        {
          "delivery": 5,
          "checks": "Duplicate delivery",
          "note": "The same event arrives again, as at-least-once delivery allows. Same source and id: it is ignored."
        },
        {
          "delivery": 6,
          "checks": "Task context",
          "note": "The housekeeping system creates cleaning task task_88 for unit 204. Its causal link points to the departure status change."
        },
        {
          "delivery": 7,
          "checks": "Missing capability",
          "note": "The PMS publishes a housekeeping task, but its manifest does not declare that capability at this property. Undeclared means denied: HOS ignores it."
        },
        {
          "delivery": 8,
          "checks": "A task is not a status",
          "note": "Task task_88 is reported complete. At this property only the supervisor's inspection releases a unit, so the authoritative status is still dirty."
        },
        {
          "delivery": 9,
          "checks": "Conflicting facts",
          "note": "The PMS flips unit 204 to clean because the task closed. Its manifest declares it non-authoritative for housekeeping, so HOS records the disagreement instead of merging it. A front desk trusting the PMS would hand over a room nobody released."
        },
        {
          "delivery": 10,
          "checks": "Risk detection",
          "note": "At 11:40 the guest writes that they will arrive around 12:30, before the 15:00 check-in. Only the extracted signal travels, not the message. The unit is not ready: the reference projection raises arrival.room_readiness_at_risk with its evidence."
        },
        {
          "delivery": 11,
          "checks": "Out-of-order delivery",
          "note": "An earlier message (11:05, arriving 12:00) is delivered late. Its signal is older than the 11:40 one, so it does not replace it."
        },
        {
          "delivery": 12,
          "checks": "Snapshot recovery",
          "note": "The housekeeping webhook was down while the supervisor inspected unit 204. On recovery the system sends an explicit, sensitivity-classified snapshot. The authoritative status becomes inspected: the risk is resolved 14 minutes before the guest arrives."
        },
        {
          "delivery": 13,
          "checks": "Stay started",
          "note": "The guest checks in at 12:35 into an inspected unit."
        }
      ]
    },
    "manifests": [
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:pms:demo",
        "name": "Synthetic PMS",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "pms",
        "property_ids": [
          "prop_demo"
        ],
        "entities": [
          "Reservation",
          "Stay",
          "Unit",
          "Guest"
        ],
        "events": [
          {
            "type": "reservation.created",
            "authoritative": true
          },
          {
            "type": "reservation.updated",
            "authoritative": true
          },
          {
            "type": "reservation.cancelled",
            "authoritative": true
          },
          {
            "type": "stay.expected",
            "authoritative": true
          },
          {
            "type": "stay.unit_assigned",
            "authoritative": true
          },
          {
            "type": "stay.checked_in",
            "authoritative": true
          },
          {
            "type": "stay.check_in_reverted",
            "authoritative": true
          },
          {
            "type": "stay.checked_out",
            "authoritative": true
          },
          {
            "type": "stay.unit_unassigned",
            "authoritative": true
          },
          {
            "type": "unit.maintenance_scheduled",
            "authoritative": true
          },
          {
            "type": "unit.maintenance_cancelled",
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy",
              "commercial"
            ],
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": false,
            "note": "The PMS mirrors housekeeping status; at this property the housekeeping system is the authority."
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "per-subject"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 90
        },
        "limitations": [
          "The PMS task module is not a declared source of housekeeping tasks at this property.",
          "Guest messages are not exposed."
        ]
      },
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:housekeeping:demo",
        "name": "Synthetic housekeeping system",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "housekeeping",
        "property_ids": [
          "prop_demo"
        ],
        "entities": [
          "Unit",
          "Task"
        ],
        "events": [
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": true,
            "snapshot": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy"
            ],
            "authoritative": false,
            "snapshot": true,
            "note": "Occupancy is reported for context; the PMS is the authority."
          },
          {
            "type": "housekeeping.task.created",
            "authoritative": true
          },
          {
            "type": "housekeeping.task.completed",
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "none"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 30
        },
        "limitations": [
          "The property releases units on inspection only, so the housekeeping status goes from dirty to inspected without a clean step."
        ]
      },
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:messaging:demo",
        "name": "Synthetic guest messaging platform",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "messaging",
        "property_ids": [
          "prop_demo"
        ],
        "entities": [
          "Message",
          "Guest"
        ],
        "events": [
          {
            "type": "guest.message.received",
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "none"
        },
        "replay": {
          "supported": false
        },
        "retention": {
          "event_days": 7
        },
        "limitations": [
          "Signals are extracted automatically from free text and carry a confidence.",
          "Replay is not available; a certified Event Producer profile requires at least 30 days."
        ]
      }
    ],
    "events": [
      {
        "specversion": "1.0",
        "id": "pms-000312",
        "source": "urn:hos:pms:demo",
        "type": "reservation.created",
        "time": "2026-07-12T14:03:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-12T14:03:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-12",
        "hossubjects": "reservation:res_1042 guest:guest_7q2k",
        "data": {
          "reservation_id": "res_1042",
          "status": "confirmed",
          "planned_arrival_date": "2026-07-30",
          "planned_departure_date": "2026-08-01",
          "guest_id": "guest_7q2k",
          "external_refs": [
            {
              "source_system": "urn:hos:pms:demo",
              "id_type": "confirmation_number",
              "source_id": "DEMO-1042",
              "verification": "verified"
            }
          ]
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-000421",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-07-30T06:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T06:05:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "stay:stay_1042 reservation:res_1042 guest:guest_7q2k",
        "data": {
          "stay_id": "stay_1042",
          "reservation_id": "res_1042",
          "guest_id": "guest_7q2k",
          "planned_arrival_at": "2026-07-30T13:00:00Z",
          "planned_departure_at": "2026-08-01T09:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-000422",
        "source": "urn:hos:pms:demo",
        "type": "stay.unit_assigned",
        "time": "2026-07-30T06:06:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T06:06:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "stay:stay_1042 unit:unit_204",
        "data": {
          "stay_id": "stay_1042",
          "unit_id": "unit_204",
          "previous_unit_id": null,
          "reason": "initial_assignment"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-002231",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-07-30T06:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T06:40:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "unit:unit_204",
        "data": {
          "unit_id": "unit_204",
          "dimension": "housekeeping",
          "previous": "inspected",
          "current": "dirty",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "departure"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-002231",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-07-30T06:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T06:40:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "unit:unit_204",
        "data": {
          "unit_id": "unit_204",
          "dimension": "housekeeping",
          "previous": "inspected",
          "current": "dirty",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "departure"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-002232",
        "source": "urn:hos:housekeeping:demo",
        "type": "housekeeping.task.created",
        "time": "2026-07-30T06:45:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T06:45:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "task:task_88 unit:unit_204",
        "hoscausationsource": "urn:hos:housekeeping:demo",
        "hoscausationid": "hk-002231",
        "data": {
          "task_id": "task_88",
          "unit_id": "unit_204",
          "task_type": "cleaning",
          "priority": "normal",
          "due_at": "2026-07-30T13:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-000430",
        "source": "urn:hos:pms:demo",
        "type": "housekeeping.task.created",
        "time": "2026-07-30T07:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T07:30:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "task:task_pms_17 unit:unit_204",
        "data": {
          "task_id": "task_pms_17",
          "unit_id": "unit_204",
          "task_type": "inspection",
          "priority": "normal"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-002260",
        "source": "urn:hos:housekeeping:demo",
        "type": "housekeeping.task.completed",
        "time": "2026-07-30T08:20:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T08:20:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "task:task_88 unit:unit_204",
        "data": {
          "task_id": "task_88",
          "unit_id": "unit_204",
          "task_type": "cleaning",
          "completed_by_ref": "staff_k3"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-000455",
        "source": "urn:hos:pms:demo",
        "type": "unit.status_changed",
        "time": "2026-07-30T08:21:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T08:21:03Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "unit:unit_204",
        "hoscausationsource": "urn:hos:housekeeping:demo",
        "hoscausationid": "hk-002260",
        "data": {
          "unit_id": "unit_204",
          "dimension": "housekeeping",
          "previous": "dirty",
          "current": "clean",
          "authority_source": "urn:hos:pms:demo",
          "reason": "cleaning_completed"
        }
      },
      {
        "specversion": "1.0",
        "id": "msg-000977",
        "source": "urn:hos:messaging:demo",
        "type": "guest.message.received",
        "time": "2026-07-30T09:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T09:40:04Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "message:msg_51_2 stay:stay_1042 guest:guest_7q2k",
        "data": {
          "message_id": "msg_51_2",
          "channel": "messaging_app",
          "guest_id": "guest_7q2k",
          "stay_id": "stay_1042",
          "sensitivity": "confidential",
          "signals": [
            {
              "kind": "early_arrival",
              "expected_arrival_at": "2026-07-30T10:30:00Z",
              "confidence": 0.92
            }
          ]
        }
      },
      {
        "specversion": "1.0",
        "id": "msg-000971",
        "source": "urn:hos:messaging:demo",
        "type": "guest.message.received",
        "time": "2026-07-30T09:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T09:05:06Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "message:msg_51_1 stay:stay_1042 guest:guest_7q2k",
        "data": {
          "message_id": "msg_51_1",
          "channel": "messaging_app",
          "guest_id": "guest_7q2k",
          "stay_id": "stay_1042",
          "sensitivity": "confidential",
          "signals": [
            {
              "kind": "early_arrival",
              "expected_arrival_at": "2026-07-30T10:00:00Z",
              "confidence": 0.88
            }
          ]
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-002301",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-07-30T10:16:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T10:16:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "unit:unit_204",
        "hosdatamode": "snapshot",
        "hossensitivity": "internal",
        "data": {
          "unit_id": "unit_204",
          "statuses": {
            "housekeeping": "inspected",
            "occupancy": "vacant"
          },
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "recovery"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-000470",
        "source": "urn:hos:pms:demo",
        "type": "stay.checked_in",
        "time": "2026-07-30T10:35:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-30T10:35:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_demo",
        "hospropertytimezone": "Europe/Paris",
        "hosbusinessdate": "2026-07-30",
        "hossubjects": "stay:stay_1042 unit:unit_204",
        "data": {
          "stay_id": "stay_1042",
          "unit_id": "unit_204"
        }
      }
    ],
    "expected": {
      "scenario": "arrival-readiness",
      "hosschemaversion": "0.1",
      "compare": "Replay events.jsonl in file order. For every delivery compare the disposition and, for every known stay, its readiness and situation. For situations compare every attribute except id and hosrecordedat, which are implementation-defined.",
      "deliveries": [
        {
          "delivery": 1,
          "source": "urn:hos:pms:demo",
          "id": "pms-000312",
          "disposition": "applied",
          "stays": {}
        },
        {
          "delivery": 2,
          "source": "urn:hos:pms:demo",
          "id": "pms-000421",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 3,
          "source": "urn:hos:pms:demo",
          "id": "pms-000422",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 4,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-002231",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 5,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-002231",
          "disposition": "duplicate",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 6,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-002232",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 7,
          "source": "urn:hos:pms:demo",
          "id": "pms-000430",
          "disposition": "undeclared_capability",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 8,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-002260",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 9,
          "source": "urn:hos:pms:demo",
          "id": "pms-000455",
          "disposition": "non_authoritative",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 10,
          "source": "urn:hos:messaging:demo",
          "id": "msg-000977",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 11,
          "source": "urn:hos:messaging:demo",
          "id": "msg-000971",
          "disposition": "superseded",
          "stays": {
            "stay_1042": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 12,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-002301",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 13,
          "source": "urn:hos:pms:demo",
          "id": "pms-000470",
          "disposition": "applied",
          "stays": {
            "stay_1042": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        }
      ],
      "situations": [
        {
          "delivery": 10,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_at_risk",
            "time": "2026-07-30T09:40:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_demo",
            "hospropertytimezone": "Europe/Paris",
            "hosbusinessdate": "2026-07-30",
            "hossubjects": "stay:stay_1042 reservation:res_1042 unit:unit_204",
            "hoscausationsource": "urn:hos:messaging:demo",
            "hoscausationid": "msg-000977",
            "data": {
              "stay_id": "stay_1042",
              "reservation_id": "res_1042",
              "unit_id": "unit_204",
              "planned_arrival_at": "2026-07-30T13:00:00Z",
              "expected_arrival_at": "2026-07-30T10:30:00Z",
              "housekeeping": {
                "value": "dirty",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-002231",
                "time": "2026-07-30T06:40:00Z"
              },
              "conflicts": [
                {
                  "dimension": "housekeeping",
                  "value": "clean",
                  "source": "urn:hos:pms:demo",
                  "event_id": "pms-000455",
                  "time": "2026-07-30T08:21:00Z"
                }
              ],
              "latest_task": {
                "task_id": "task_88",
                "task_type": "cleaning",
                "status": "completed",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-002260",
                "time": "2026-07-30T08:20:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000312"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000421"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000422"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-002231"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-002260"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000455"
                },
                {
                  "source": "urn:hos:messaging:demo",
                  "id": "msg-000977"
                }
              ]
            }
          }
        },
        {
          "delivery": 12,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_resolved",
            "time": "2026-07-30T10:16:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_demo",
            "hospropertytimezone": "Europe/Paris",
            "hosbusinessdate": "2026-07-30",
            "hossubjects": "stay:stay_1042 reservation:res_1042 unit:unit_204",
            "hoscausationsource": "urn:hos:housekeeping:demo",
            "hoscausationid": "hk-002301",
            "data": {
              "stay_id": "stay_1042",
              "reservation_id": "res_1042",
              "unit_id": "unit_204",
              "reason": "unit_ready",
              "planned_arrival_at": "2026-07-30T13:00:00Z",
              "expected_arrival_at": "2026-07-30T10:30:00Z",
              "housekeeping": {
                "value": "inspected",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-002301",
                "time": "2026-07-30T10:16:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000312"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000421"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-000422"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-002260"
                },
                {
                  "source": "urn:hos:messaging:demo",
                  "id": "msg-000977"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-002301"
                }
              ]
            }
          }
        }
      ]
    }
  },
  "late-checkout": {
    "scenario": {
      "scenario": "late-checkout",
      "hosschemaversion": "0.1",
      "status": "draft",
      "title": "Late check-out on a same-day turnover",
      "summary": "Synthetic facts from a PMS and a housekeeping system for one property. A late check-out is granted in a unit already assigned to an arrival the same day. Replay events.jsonl in file order through an implementation and compare its dispositions, readiness and situations with expected.json. The situations are non-normative; the dispositions follow the HOS Events 0.1 processing rules.",
      "covers": [
        "A unit held by another guest in house is not ready",
        "Late check-out overlapping a same-day arrival",
        "Occupancy observed by a non-authoritative producer",
        "Latest plan wins: an older stay plan replayed late is superseded",
        "Delivery order differs from occurrence order",
        "Check-out resolves the risk"
      ],
      "tenant": {
        "id": "tenant_demo"
      },
      "property": {
        "id": "prop_toronto",
        "timezone": "America/Toronto",
        "country": "CA"
      },
      "projection": {
        "ready_housekeeping_statuses": [
          "clean",
          "inspected"
        ]
      },
      "files": {
        "events": "events.jsonl",
        "expected": "expected.json",
        "producers": [
          "producers/pms.json",
          "producers/housekeeping.json"
        ]
      },
      "deliveries": [
        {
          "delivery": 1,
          "checks": "Departing stay",
          "note": "Stay stay_3088 was booked on 30 June, from 18 August at 16:00 to 21 August at the standard 11:00 check-out."
        },
        {
          "delivery": 2,
          "checks": "Departing unit",
          "note": "The PMS assigned unit 1207 to stay_3088 on 18 August."
        },
        {
          "delivery": 3,
          "checks": "Guest in house",
          "note": "The guest of stay_3088 checked in on 18 August at 17:10."
        },
        {
          "delivery": 4,
          "checks": "Arriving reservation",
          "note": "The PMS created reservation res_3140 on 3 August for an arrival on 21 August."
        },
        {
          "delivery": 5,
          "checks": "Arriving stay",
          "note": "Stay stay_3140 is expected on 21 August at the standard 16:00 check-in."
        },
        {
          "delivery": 6,
          "checks": "Held unit is not ready",
          "note": "At 07:30 on 21 August the PMS assigns unit 1207 to the arriving stay: a same-day turnover. The guest of stay_3088 still holds the unit, so it is not ready. That guest is due to leave at 11:00, before the arrival, so there is no situation."
        },
        {
          "delivery": 7,
          "checks": "Late check-out overlaps",
          "note": "At 09:15 a front-desk agent grants stay_3088 a late check-out at 17:00. The PMS publishes the stay's new planned times. The guest in house is now due to leave after the 16:00 check-in: the reference projection raises arrival.room_readiness_at_risk, naming the stay that holds the unit."
        },
        {
          "delivery": 8,
          "checks": "Occupancy observed, not decided",
          "note": "At 12:40 a room attendant finds unit 1207 empty and reports it vacant. The housekeeping manifest declares occupancy non-authoritative: the guest may only be out, luggage still in the room. Only the PMS says who holds the unit."
        },
        {
          "delivery": 9,
          "checks": "Older plan, replayed late",
          "note": "A PMS replay delivers the stay's plan from 20 August, with the 11:00 check-out. Applied, it would make the risk seem resolved. It is older than the late check-out, so it is superseded."
        },
        {
          "delivery": 10,
          "checks": "Delivery order",
          "note": "The housekeeping system reports unit 1207 dirty after the departure at 13:55, before the PMS check-out reaches HOS. It changes the housekeeping status only: the PMS still says the guest holds the unit, so the risk remains."
        },
        {
          "delivery": 11,
          "checks": "Check-out resolves",
          "note": "The PMS check-out, which occurred at 13:50, arrives late. The unit is vacated before the arrival: the risk is resolved as unit_vacated. The unit is dirty, but the guest is expected at 16:00, not earlier."
        },
        {
          "delivery": 12,
          "checks": "Turnover task",
          "note": "The housekeeping system opens a high-priority cleaning task, due at check-in. Its causal link points to the dirty status."
        },
        {
          "delivery": 13,
          "checks": "Task is not a status",
          "note": "The cleaning is done at 15:05. At this property only an inspection releases a unit, so it is still dirty."
        },
        {
          "delivery": 14,
          "checks": "Unit released",
          "note": "Unit 1207 is inspected at 15:20. The arriving stay is ready."
        },
        {
          "delivery": 15,
          "checks": "Stay started",
          "note": "The guest of stay_3140 checks in at 16:10."
        }
      ]
    },
    "manifests": [
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:pms:demo",
        "name": "Synthetic PMS",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "pms",
        "property_ids": [
          "prop_toronto"
        ],
        "entities": [
          "Reservation",
          "Stay",
          "Unit",
          "Guest"
        ],
        "events": [
          {
            "type": "reservation.created",
            "authoritative": true
          },
          {
            "type": "reservation.updated",
            "authoritative": true
          },
          {
            "type": "reservation.cancelled",
            "authoritative": true
          },
          {
            "type": "stay.expected",
            "authoritative": true
          },
          {
            "type": "stay.unit_assigned",
            "authoritative": true
          },
          {
            "type": "stay.unit_unassigned",
            "authoritative": true
          },
          {
            "type": "stay.checked_in",
            "authoritative": true
          },
          {
            "type": "stay.check_in_reverted",
            "authoritative": true
          },
          {
            "type": "stay.checked_out",
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy",
              "commercial"
            ],
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": false,
            "note": "The PMS mirrors housekeeping status; the housekeeping system is the authority."
          },
          {
            "type": "unit.maintenance_scheduled",
            "authoritative": true
          },
          {
            "type": "unit.maintenance_cancelled",
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "per-subject"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 90
        },
        "limitations": [
          "Late check-outs are granted at the front desk by moving the planned departure."
        ]
      },
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:housekeeping:demo",
        "name": "Synthetic housekeeping system",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "housekeeping",
        "property_ids": [
          "prop_toronto"
        ],
        "entities": [
          "Unit",
          "Task"
        ],
        "events": [
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": true,
            "snapshot": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy"
            ],
            "authoritative": false,
            "snapshot": true,
            "note": "Room attendants report what they see; the PMS is the occupancy authority."
          },
          {
            "type": "housekeeping.task.created",
            "authoritative": true
          },
          {
            "type": "housekeeping.task.completed",
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "none"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 30
        },
        "limitations": [
          "Units are released on inspection.",
          "Occupancy comes from room attendants' visual checks."
        ]
      }
    ],
    "events": [
      {
        "specversion": "1.0",
        "id": "pms-030880",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-06-30T18:20:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-06-30T18:20:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-18",
        "hossubjects": "stay:stay_3088 reservation:res_3088 guest:guest_d2w9",
        "data": {
          "stay_id": "stay_3088",
          "reservation_id": "res_3088",
          "guest_id": "guest_d2w9",
          "planned_arrival_at": "2026-08-18T20:00:00Z",
          "planned_departure_at": "2026-08-21T15:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031204",
        "source": "urn:hos:pms:demo",
        "type": "stay.unit_assigned",
        "time": "2026-08-18T17:45:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-18T17:45:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-18",
        "hossubjects": "stay:stay_3088 unit:unit_1207",
        "data": {
          "stay_id": "stay_3088",
          "unit_id": "unit_1207",
          "previous_unit_id": null,
          "reason": "initial_assignment"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031219",
        "source": "urn:hos:pms:demo",
        "type": "stay.checked_in",
        "time": "2026-08-18T21:10:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-18T21:10:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-18",
        "hossubjects": "stay:stay_3088 unit:unit_1207",
        "data": {
          "stay_id": "stay_3088",
          "unit_id": "unit_1207"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-030955",
        "source": "urn:hos:pms:demo",
        "type": "reservation.created",
        "time": "2026-08-03T13:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-03T13:30:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-03",
        "hossubjects": "reservation:res_3140 guest:guest_a6r1",
        "data": {
          "reservation_id": "res_3140",
          "status": "confirmed",
          "planned_arrival_date": "2026-08-21",
          "planned_departure_date": "2026-08-23",
          "guest_id": "guest_a6r1",
          "external_refs": [
            {
              "source_system": "urn:hos:pms:demo",
              "id_type": "confirmation_number",
              "source_id": "DEMO-3140",
              "verification": "verified"
            }
          ]
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-030956",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-08-03T13:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-03T13:30:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "stay:stay_3140 reservation:res_3140 guest:guest_a6r1",
        "data": {
          "stay_id": "stay_3140",
          "reservation_id": "res_3140",
          "guest_id": "guest_a6r1",
          "planned_arrival_at": "2026-08-21T20:00:00Z",
          "planned_departure_at": "2026-08-23T15:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031402",
        "source": "urn:hos:pms:demo",
        "type": "stay.unit_assigned",
        "time": "2026-08-21T11:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T11:30:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "stay:stay_3140 unit:unit_1207",
        "data": {
          "stay_id": "stay_3140",
          "unit_id": "unit_1207",
          "previous_unit_id": null,
          "reason": "initial_assignment"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031418",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-08-21T13:15:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T13:15:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-18",
        "hossubjects": "stay:stay_3088 reservation:res_3088 guest:guest_d2w9",
        "hosactor": "user:staff_j7",
        "data": {
          "stay_id": "stay_3088",
          "reservation_id": "res_3088",
          "guest_id": "guest_d2w9",
          "planned_arrival_at": "2026-08-18T20:00:00Z",
          "planned_departure_at": "2026-08-21T21:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-007815",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-21T16:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T16:40:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "unit:unit_1207",
        "data": {
          "unit_id": "unit_1207",
          "dimension": "occupancy",
          "previous": "occupied",
          "current": "vacant",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "other"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031377",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-08-20T22:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-20T22:05:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-18",
        "hossubjects": "stay:stay_3088 reservation:res_3088 guest:guest_d2w9",
        "data": {
          "stay_id": "stay_3088",
          "reservation_id": "res_3088",
          "guest_id": "guest_d2w9",
          "planned_arrival_at": "2026-08-18T20:00:00Z",
          "planned_departure_at": "2026-08-21T15:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-007830",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-21T17:55:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T17:55:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "unit:unit_1207",
        "data": {
          "unit_id": "unit_1207",
          "dimension": "housekeeping",
          "current": "dirty",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "departure"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031466",
        "source": "urn:hos:pms:demo",
        "type": "stay.checked_out",
        "time": "2026-08-21T17:50:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T17:57:00Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "stay:stay_3088 unit:unit_1207",
        "data": {
          "stay_id": "stay_3088",
          "unit_id": "unit_1207"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-007831",
        "source": "urn:hos:housekeeping:demo",
        "type": "housekeeping.task.created",
        "time": "2026-08-21T17:56:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T17:56:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "task:task_412 unit:unit_1207 stay:stay_3140",
        "hoscausationsource": "urn:hos:housekeeping:demo",
        "hoscausationid": "hk-007830",
        "data": {
          "task_id": "task_412",
          "unit_id": "unit_1207",
          "stay_id": "stay_3140",
          "task_type": "cleaning",
          "priority": "high",
          "due_at": "2026-08-21T20:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-007862",
        "source": "urn:hos:housekeeping:demo",
        "type": "housekeeping.task.completed",
        "time": "2026-08-21T19:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T19:05:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "task:task_412 unit:unit_1207",
        "data": {
          "task_id": "task_412",
          "unit_id": "unit_1207",
          "task_type": "cleaning",
          "completed_by_ref": "staff_p4"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-007870",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-21T19:20:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T19:20:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "unit:unit_1207",
        "data": {
          "unit_id": "unit_1207",
          "dimension": "housekeeping",
          "previous": "dirty",
          "current": "inspected",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "inspection"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-031490",
        "source": "urn:hos:pms:demo",
        "type": "stay.checked_in",
        "time": "2026-08-21T20:10:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-21T20:10:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_toronto",
        "hospropertytimezone": "America/Toronto",
        "hosbusinessdate": "2026-08-21",
        "hossubjects": "stay:stay_3140 unit:unit_1207",
        "data": {
          "stay_id": "stay_3140",
          "unit_id": "unit_1207"
        }
      }
    ],
    "expected": {
      "scenario": "late-checkout",
      "hosschemaversion": "0.1",
      "compare": "Replay events.jsonl in file order. For every delivery compare the disposition and, for every known stay, its readiness and situation. For situations compare every attribute except id and hosrecordedat, which are implementation-defined.",
      "deliveries": [
        {
          "delivery": 1,
          "source": "urn:hos:pms:demo",
          "id": "pms-030880",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 2,
          "source": "urn:hos:pms:demo",
          "id": "pms-031204",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 3,
          "source": "urn:hos:pms:demo",
          "id": "pms-031219",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 4,
          "source": "urn:hos:pms:demo",
          "id": "pms-030955",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 5,
          "source": "urn:hos:pms:demo",
          "id": "pms-030956",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 6,
          "source": "urn:hos:pms:demo",
          "id": "pms-031402",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 7,
          "source": "urn:hos:pms:demo",
          "id": "pms-031418",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 8,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-007815",
          "disposition": "non_authoritative",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 9,
          "source": "urn:hos:pms:demo",
          "id": "pms-031377",
          "disposition": "superseded",
          "stays": {
            "stay_3088": {
              "readiness": "unknown",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 10,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-007830",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "not_ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 11,
          "source": "urn:hos:pms:demo",
          "id": "pms-031466",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "not_ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 12,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-007831",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "not_ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 13,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-007862",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "not_ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "not_ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 14,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-007870",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 15,
          "source": "urn:hos:pms:demo",
          "id": "pms-031490",
          "disposition": "applied",
          "stays": {
            "stay_3088": {
              "readiness": "ready",
              "situation": "none"
            },
            "stay_3140": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        }
      ],
      "situations": [
        {
          "delivery": 7,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_at_risk",
            "time": "2026-08-21T13:15:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_toronto",
            "hospropertytimezone": "America/Toronto",
            "hosbusinessdate": "2026-08-21",
            "hossubjects": "stay:stay_3140 reservation:res_3140 unit:unit_1207",
            "hoscausationsource": "urn:hos:pms:demo",
            "hoscausationid": "pms-031418",
            "data": {
              "stay_id": "stay_3140",
              "reservation_id": "res_3140",
              "unit_id": "unit_1207",
              "planned_arrival_at": "2026-08-21T20:00:00Z",
              "expected_arrival_at": "2026-08-21T20:00:00Z",
              "housekeeping": null,
              "conflicts": [],
              "latest_task": null,
              "occupied_by": {
                "stay_id": "stay_3088",
                "planned_departure_at": "2026-08-21T21:00:00Z",
                "source": "urn:hos:pms:demo",
                "event_id": "pms-031219",
                "time": "2026-08-18T21:10:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-030955"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-030956"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031204"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031219"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031402"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031418"
                }
              ]
            }
          }
        },
        {
          "delivery": 11,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_resolved",
            "time": "2026-08-21T17:55:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_toronto",
            "hospropertytimezone": "America/Toronto",
            "hosbusinessdate": "2026-08-21",
            "hossubjects": "stay:stay_3140 reservation:res_3140 unit:unit_1207",
            "hoscausationsource": "urn:hos:pms:demo",
            "hoscausationid": "pms-031466",
            "data": {
              "stay_id": "stay_3140",
              "reservation_id": "res_3140",
              "unit_id": "unit_1207",
              "reason": "unit_vacated",
              "planned_arrival_at": "2026-08-21T20:00:00Z",
              "expected_arrival_at": null,
              "housekeeping": {
                "value": "dirty",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-007830",
                "time": "2026-08-21T17:55:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-030955"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-030956"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031402"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-031466"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-007830"
                }
              ]
            }
          }
        }
      ]
    }
  },
  "room-out-of-order": {
    "scenario": {
      "scenario": "room-out-of-order",
      "hosschemaversion": "0.1",
      "status": "draft",
      "title": "Assigned unit out of order",
      "summary": "Synthetic facts from a PMS, a housekeeping system and a maintenance system for one property. On the arrival day, a leak takes the guest's assigned unit out of order. Replay events.jsonl in file order through an implementation and compare its dispositions, readiness and situations with expected.json. The situations are non-normative; the dispositions follow the HOS Events 0.1 processing rules.",
      "covers": [
        "Maintenance window blocking an assigned arrival",
        "A plan is not a state: the window and the maintenance status travel separately",
        "Mirrored maintenance plan from a non-authoritative producer",
        "Latest plan wins: an older revision delivered late is superseded",
        "Reassignment resolves the risk",
        "Causation across producers"
      ],
      "tenant": {
        "id": "tenant_demo"
      },
      "property": {
        "id": "prop_lisbon",
        "timezone": "Europe/Lisbon",
        "country": "PT"
      },
      "projection": {
        "ready_housekeeping_statuses": [
          "clean",
          "inspected"
        ]
      },
      "files": {
        "events": "events.jsonl",
        "expected": "expected.json",
        "producers": [
          "producers/pms.json",
          "producers/housekeeping.json",
          "producers/maintenance.json"
        ]
      },
      "deliveries": [
        {
          "delivery": 1,
          "checks": "Reservation context",
          "note": "The PMS created reservation res_2051 on 2 July for an arrival on 14 August."
        },
        {
          "delivery": 2,
          "checks": "Stay context",
          "note": "The PMS published the stay with the reservation, as HOS Events requires once a stay is committed: stay_2051 is expected at the standard 15:00 check-in."
        },
        {
          "delivery": 3,
          "checks": "Unit assignment",
          "note": "On the arrival morning the PMS assigns unit 312."
        },
        {
          "delivery": 4,
          "checks": "Ready unit",
          "note": "The housekeeping system, the authority for housekeeping status, reports unit 312 inspected. The stay is ready, with no situation."
        },
        {
          "delivery": 5,
          "checks": "Window blocks an arrival",
          "note": "At 09:40 a leak is reported under the bathroom sink. The maintenance system, the declared authority for maintenance windows, plans a repair from 09:45 to 16:00. The window covers the 15:00 check-in, so the reference projection raises arrival.room_readiness_at_risk, citing the window. No arrival signal is needed."
        },
        {
          "delivery": 6,
          "checks": "A plan is not a state",
          "note": "The work starts and the maintenance system reports unit 312 out of service. The window planned the work; this status says what the unit is now. Only the maintenance dimension changes."
        },
        {
          "delivery": 7,
          "checks": "Mirrored plan",
          "note": "A front-desk agent copies the repair into a PMS out-of-order block, planned in days. The PMS manifest declares it a mirror, not the authority for maintenance windows: HOS records it as not authoritative and does not count the work twice."
        },
        {
          "delivery": 8,
          "checks": "Another unit",
          "note": "Unit 318 is reported dirty after its guest left. It concerns no expected stay yet."
        },
        {
          "delivery": 9,
          "checks": "Plan revised",
          "note": "At 11:30 the plumber needs a part: the maintenance system moves the end of the window to 19:00. The latest plan for mnt_77 applies, and the risk remains."
        },
        {
          "delivery": 10,
          "checks": "Older plan, delivered late",
          "note": "A revision entered offline at 10:20 syncs after the 11:30 one. It ends the window at 14:30, before check-in: applied, it would make the risk seem resolved. It is older than the current plan, so it is superseded."
        },
        {
          "delivery": 11,
          "checks": "Reassignment resolves",
          "note": "The front desk moves the stay to unit 318. The window no longer concerns the stay: the risk is resolved as unit_reassigned. Unit 318 is dirty, but check-in is at 15:00 and nothing says the guest comes early."
        },
        {
          "delivery": 12,
          "checks": "Causation across producers",
          "note": "The housekeeping system opens a high-priority cleaning task for unit 318, due at check-in. Its causal link points to the PMS reassignment."
        },
        {
          "delivery": 13,
          "checks": "Unit released",
          "note": "Unit 318 is inspected at 13:40. The stay is ready."
        },
        {
          "delivery": 14,
          "checks": "Stay started",
          "note": "The guest checks in at 15:10 into unit 318."
        }
      ]
    },
    "manifests": [
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:pms:demo",
        "name": "Synthetic PMS",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "pms",
        "property_ids": [
          "prop_lisbon"
        ],
        "entities": [
          "Reservation",
          "Stay",
          "Unit",
          "Guest"
        ],
        "events": [
          {
            "type": "reservation.created",
            "authoritative": true
          },
          {
            "type": "reservation.updated",
            "authoritative": true
          },
          {
            "type": "reservation.cancelled",
            "authoritative": true
          },
          {
            "type": "stay.expected",
            "authoritative": true
          },
          {
            "type": "stay.unit_assigned",
            "authoritative": true
          },
          {
            "type": "stay.unit_unassigned",
            "authoritative": true
          },
          {
            "type": "stay.checked_in",
            "authoritative": true
          },
          {
            "type": "stay.check_in_reverted",
            "authoritative": true
          },
          {
            "type": "stay.checked_out",
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy",
              "commercial"
            ],
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": false,
            "note": "The PMS mirrors housekeeping status; the housekeeping system is the authority."
          },
          {
            "type": "unit.maintenance_scheduled",
            "authoritative": false,
            "note": "Front-desk staff copy maintenance work into PMS out-of-order blocks, planned in days. The maintenance system is the authority for maintenance windows."
          },
          {
            "type": "unit.maintenance_cancelled",
            "authoritative": false,
            "note": "See unit.maintenance_scheduled."
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "per-subject"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 90
        },
        "limitations": [
          "Out-of-order blocks are planned in days and entered by hand."
        ]
      },
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:housekeeping:demo",
        "name": "Synthetic housekeeping system",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "housekeeping",
        "property_ids": [
          "prop_lisbon"
        ],
        "entities": [
          "Unit",
          "Task"
        ],
        "events": [
          {
            "type": "unit.status_changed",
            "dimensions": [
              "housekeeping"
            ],
            "authoritative": true,
            "snapshot": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "occupancy"
            ],
            "authoritative": false,
            "snapshot": true,
            "note": "Room attendants report what they see; the PMS is the occupancy authority."
          },
          {
            "type": "housekeeping.task.created",
            "authoritative": true
          },
          {
            "type": "housekeeping.task.completed",
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "none"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 30
        },
        "limitations": [
          "Units are released on inspection."
        ]
      },
      {
        "hosmanifestversion": "0.1",
        "producer": "urn:hos:maintenance:demo",
        "name": "Synthetic maintenance system",
        "organization": {
          "name": "HOS AI synthetic corpus"
        },
        "system_role": "maintenance",
        "property_ids": [
          "prop_lisbon"
        ],
        "entities": [
          "Unit",
          "MaintenanceWindow"
        ],
        "events": [
          {
            "type": "unit.maintenance_scheduled",
            "authoritative": true
          },
          {
            "type": "unit.maintenance_cancelled",
            "authoritative": true
          },
          {
            "type": "unit.status_changed",
            "dimensions": [
              "maintenance"
            ],
            "authoritative": true
          }
        ],
        "delivery": {
          "mechanisms": [
            "webhook"
          ],
          "guarantee": "at-least-once",
          "ordering": "none"
        },
        "replay": {
          "supported": true,
          "window_days": 30,
          "format": "jsonl"
        },
        "retention": {
          "event_days": 365
        },
        "limitations": [
          "Technicians can update a window offline; the update is recorded and delivered when their device syncs.",
          "The maintenance system does not know reservations or stays."
        ]
      }
    ],
    "events": [
      {
        "specversion": "1.0",
        "id": "pms-020114",
        "source": "urn:hos:pms:demo",
        "type": "reservation.created",
        "time": "2026-07-02T09:12:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-02T09:12:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-07-02",
        "hossubjects": "reservation:res_2051 guest:guest_m4p8",
        "data": {
          "reservation_id": "res_2051",
          "status": "confirmed",
          "planned_arrival_date": "2026-08-14",
          "planned_departure_date": "2026-08-17",
          "guest_id": "guest_m4p8",
          "external_refs": [
            {
              "source_system": "urn:hos:pms:demo",
              "id_type": "confirmation_number",
              "source_id": "DEMO-2051",
              "verification": "verified"
            }
          ]
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-020115",
        "source": "urn:hos:pms:demo",
        "type": "stay.expected",
        "time": "2026-07-02T09:12:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-07-02T09:12:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "stay:stay_2051 reservation:res_2051 guest:guest_m4p8",
        "data": {
          "stay_id": "stay_2051",
          "reservation_id": "res_2051",
          "guest_id": "guest_m4p8",
          "planned_arrival_at": "2026-08-14T14:00:00Z",
          "planned_departure_at": "2026-08-17T10:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-020301",
        "source": "urn:hos:pms:demo",
        "type": "stay.unit_assigned",
        "time": "2026-08-14T05:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T05:30:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "stay:stay_2051 unit:unit_312",
        "data": {
          "stay_id": "stay_2051",
          "unit_id": "unit_312",
          "previous_unit_id": null,
          "reason": "initial_assignment"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-005410",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-14T07:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T07:05:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "data": {
          "unit_id": "unit_312",
          "dimension": "housekeeping",
          "previous": "clean",
          "current": "inspected",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "inspection"
        }
      },
      {
        "specversion": "1.0",
        "id": "mnt-000731",
        "source": "urn:hos:maintenance:demo",
        "type": "unit.maintenance_scheduled",
        "time": "2026-08-14T08:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T08:40:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "data": {
          "maintenance_id": "mnt_77",
          "unit_id": "unit_312",
          "starts_at": "2026-08-14T08:45:00Z",
          "ends_at": "2026-08-14T15:00:00Z",
          "statuses": {
            "maintenance": "out_of_service",
            "commercial": "not_sellable"
          },
          "reason": "repair"
        }
      },
      {
        "specversion": "1.0",
        "id": "mnt-000732",
        "source": "urn:hos:maintenance:demo",
        "type": "unit.status_changed",
        "time": "2026-08-14T08:50:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T08:50:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "hoscausationsource": "urn:hos:maintenance:demo",
        "hoscausationid": "mnt-000731",
        "data": {
          "unit_id": "unit_312",
          "dimension": "maintenance",
          "previous": "operational",
          "current": "out_of_service",
          "authority_source": "urn:hos:maintenance:demo",
          "reason": "maintenance"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-020322",
        "source": "urn:hos:pms:demo",
        "type": "unit.maintenance_scheduled",
        "time": "2026-08-14T08:55:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T08:55:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "hosactor": "user:staff_f2",
        "data": {
          "maintenance_id": "mnt_pms_31",
          "unit_id": "unit_312",
          "starts_at": "2026-08-14T14:00:00Z",
          "ends_at": "2026-08-15T10:00:00Z",
          "statuses": {
            "commercial": "not_sellable"
          },
          "reason": "repair"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-005433",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-14T09:10:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T09:10:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_318",
        "data": {
          "unit_id": "unit_318",
          "dimension": "housekeeping",
          "previous": "inspected",
          "current": "dirty",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "departure"
        }
      },
      {
        "specversion": "1.0",
        "id": "mnt-000745",
        "source": "urn:hos:maintenance:demo",
        "type": "unit.maintenance_scheduled",
        "time": "2026-08-14T10:30:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T10:30:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "data": {
          "maintenance_id": "mnt_77",
          "unit_id": "unit_312",
          "starts_at": "2026-08-14T08:45:00Z",
          "ends_at": "2026-08-14T18:00:00Z",
          "statuses": {
            "maintenance": "out_of_service",
            "commercial": "not_sellable"
          },
          "reason": "repair"
        }
      },
      {
        "specversion": "1.0",
        "id": "mnt-000738",
        "source": "urn:hos:maintenance:demo",
        "type": "unit.maintenance_scheduled",
        "time": "2026-08-14T09:20:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T10:33:00Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_312",
        "data": {
          "maintenance_id": "mnt_77",
          "unit_id": "unit_312",
          "starts_at": "2026-08-14T08:45:00Z",
          "ends_at": "2026-08-14T13:30:00Z",
          "statuses": {
            "maintenance": "out_of_service",
            "commercial": "not_sellable"
          },
          "reason": "repair"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-020340",
        "source": "urn:hos:pms:demo",
        "type": "stay.unit_assigned",
        "time": "2026-08-14T11:05:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T11:05:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "stay:stay_2051 unit:unit_318",
        "hosactor": "user:staff_f2",
        "data": {
          "stay_id": "stay_2051",
          "unit_id": "unit_318",
          "previous_unit_id": "unit_312",
          "reason": "readiness"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-005470",
        "source": "urn:hos:housekeeping:demo",
        "type": "housekeeping.task.created",
        "time": "2026-08-14T11:08:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T11:08:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "task:task_130 unit:unit_318 stay:stay_2051",
        "hoscausationsource": "urn:hos:pms:demo",
        "hoscausationid": "pms-020340",
        "data": {
          "task_id": "task_130",
          "unit_id": "unit_318",
          "stay_id": "stay_2051",
          "task_type": "cleaning",
          "priority": "high",
          "due_at": "2026-08-14T14:00:00Z"
        }
      },
      {
        "specversion": "1.0",
        "id": "hk-005502",
        "source": "urn:hos:housekeeping:demo",
        "type": "unit.status_changed",
        "time": "2026-08-14T12:40:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T12:40:02Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "unit:unit_318",
        "data": {
          "unit_id": "unit_318",
          "dimension": "housekeeping",
          "previous": "dirty",
          "current": "inspected",
          "authority_source": "urn:hos:housekeeping:demo",
          "reason": "inspection"
        }
      },
      {
        "specversion": "1.0",
        "id": "pms-020377",
        "source": "urn:hos:pms:demo",
        "type": "stay.checked_in",
        "time": "2026-08-14T14:10:00Z",
        "datacontenttype": "application/json",
        "hosschemaversion": "0.1",
        "hosrecordedat": "2026-08-14T14:10:01Z",
        "hostenant": "tenant_demo",
        "hosproperty": "prop_lisbon",
        "hospropertytimezone": "Europe/Lisbon",
        "hosbusinessdate": "2026-08-14",
        "hossubjects": "stay:stay_2051 unit:unit_318",
        "data": {
          "stay_id": "stay_2051",
          "unit_id": "unit_318"
        }
      }
    ],
    "expected": {
      "scenario": "room-out-of-order",
      "hosschemaversion": "0.1",
      "compare": "Replay events.jsonl in file order. For every delivery compare the disposition and, for every known stay, its readiness and situation. For situations compare every attribute except id and hosrecordedat, which are implementation-defined.",
      "deliveries": [
        {
          "delivery": 1,
          "source": "urn:hos:pms:demo",
          "id": "pms-020114",
          "disposition": "applied",
          "stays": {}
        },
        {
          "delivery": 2,
          "source": "urn:hos:pms:demo",
          "id": "pms-020115",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 3,
          "source": "urn:hos:pms:demo",
          "id": "pms-020301",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "unknown",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 4,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-005410",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "ready",
              "situation": "none"
            }
          }
        },
        {
          "delivery": 5,
          "source": "urn:hos:maintenance:demo",
          "id": "mnt-000731",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 6,
          "source": "urn:hos:maintenance:demo",
          "id": "mnt-000732",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 7,
          "source": "urn:hos:pms:demo",
          "id": "pms-020322",
          "disposition": "non_authoritative",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 8,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-005433",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 9,
          "source": "urn:hos:maintenance:demo",
          "id": "mnt-000745",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 10,
          "source": "urn:hos:maintenance:demo",
          "id": "mnt-000738",
          "disposition": "superseded",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "at_risk"
            }
          }
        },
        {
          "delivery": 11,
          "source": "urn:hos:pms:demo",
          "id": "pms-020340",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 12,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-005470",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "not_ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 13,
          "source": "urn:hos:housekeeping:demo",
          "id": "hk-005502",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        },
        {
          "delivery": 14,
          "source": "urn:hos:pms:demo",
          "id": "pms-020377",
          "disposition": "applied",
          "stays": {
            "stay_2051": {
              "readiness": "ready",
              "situation": "resolved"
            }
          }
        }
      ],
      "situations": [
        {
          "delivery": 5,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_at_risk",
            "time": "2026-08-14T08:40:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_lisbon",
            "hospropertytimezone": "Europe/Lisbon",
            "hosbusinessdate": "2026-08-14",
            "hossubjects": "stay:stay_2051 reservation:res_2051 unit:unit_312",
            "hoscausationsource": "urn:hos:maintenance:demo",
            "hoscausationid": "mnt-000731",
            "data": {
              "stay_id": "stay_2051",
              "reservation_id": "res_2051",
              "unit_id": "unit_312",
              "planned_arrival_at": "2026-08-14T14:00:00Z",
              "expected_arrival_at": "2026-08-14T14:00:00Z",
              "housekeeping": {
                "value": "inspected",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-005410",
                "time": "2026-08-14T07:05:00Z"
              },
              "conflicts": [],
              "latest_task": null,
              "maintenance": {
                "maintenance_id": "mnt_77",
                "starts_at": "2026-08-14T08:45:00Z",
                "ends_at": "2026-08-14T15:00:00Z",
                "statuses": {
                  "maintenance": "out_of_service",
                  "commercial": "not_sellable"
                },
                "source": "urn:hos:maintenance:demo",
                "event_id": "mnt-000731",
                "time": "2026-08-14T08:40:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020114"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020115"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020301"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-005410"
                },
                {
                  "source": "urn:hos:maintenance:demo",
                  "id": "mnt-000731"
                }
              ]
            }
          }
        },
        {
          "delivery": 11,
          "event": {
            "specversion": "1.0",
            "source": "urn:hos:projection:arrival-readiness",
            "type": "arrival.room_readiness_resolved",
            "time": "2026-08-14T11:05:00Z",
            "datacontenttype": "application/json",
            "hosschemaversion": "0.1",
            "hostenant": "tenant_demo",
            "hosproperty": "prop_lisbon",
            "hospropertytimezone": "Europe/Lisbon",
            "hosbusinessdate": "2026-08-14",
            "hossubjects": "stay:stay_2051 reservation:res_2051 unit:unit_318",
            "hoscausationsource": "urn:hos:pms:demo",
            "hoscausationid": "pms-020340",
            "data": {
              "stay_id": "stay_2051",
              "reservation_id": "res_2051",
              "unit_id": "unit_318",
              "reason": "unit_reassigned",
              "planned_arrival_at": "2026-08-14T14:00:00Z",
              "expected_arrival_at": null,
              "housekeeping": {
                "value": "dirty",
                "source": "urn:hos:housekeeping:demo",
                "event_id": "hk-005433",
                "time": "2026-08-14T09:10:00Z"
              },
              "evidence": [
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020114"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020115"
                },
                {
                  "source": "urn:hos:housekeeping:demo",
                  "id": "hk-005433"
                },
                {
                  "source": "urn:hos:pms:demo",
                  "id": "pms-020340"
                }
              ]
            }
          }
        }
      ]
    }
  }
};
