// Generated by scripts/generate.ts from public/spec/0.2/schemas. Do not edit: change the published files and run
// npm run generate -w @hos-ai/sdk.

import type { AnySchemaObject } from "ajv/dist/2020.js";

export const schemasV02: Record<string, AnySchemaObject> = {
  "approval": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:approval",
    "title": "HOS Commands 0.2 approval",
    "description": "Draft. A person's decision on a command: approved or rejected. An approval names a role of the tenant, records who decided and under which role, expires, and carries the digest of the command its approver saw: a command changed afterwards no longer matches, and the approval is invalid. An approval is a document, recorded in the journal beside the command. HOS 0.2 does not sign approvals: the gateway authenticates its approvers, and signatures are left to Trust 0.3.",
    "type": "object",
    "required": [
      "hosapprovalversion",
      "approval_id",
      "command_id",
      "command_digest",
      "hostenant",
      "decision",
      "approver",
      "approver_role",
      "decided_at",
      "policy"
    ],
    "properties": {
      "hosapprovalversion": {
        "const": "0.2",
        "description": "HOS version the approval conforms to. A document with this member is an approval."
      },
      "approval_id": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
      },
      "command_id": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "The command decided on."
      },
      "command_digest": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandDigest",
        "description": "The digest of the command its approver saw."
      },
      "hostenant": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Must be the tenant of the command."
      },
      "decision": {
        "enum": [
          "approved",
          "rejected"
        ]
      },
      "approver": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/approverRef"
      },
      "approver_role": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/approverRole"
      },
      "decided_at": {
        "type": "string",
        "format": "date-time"
      },
      "expires_at": {
        "type": "string",
        "format": "date-time",
        "description": "After this instant an approval no longer authorizes the command. Required for an approval that approves."
      },
      "policy": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/policyRef",
        "description": "The policy in force when the approver decided."
      }
    },
    "if": {
      "required": [
        "decision"
      ],
      "properties": {
        "decision": {
          "const": "approved"
        }
      }
    },
    "then": {
      "required": [
        "expires_at"
      ]
    },
    "additionalProperties": false
  },
  "command-envelope": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:command-envelope",
    "title": "HOS Commands 0.2 envelope",
    "description": "Draft. A command is a document, never an event: it asks for a future mutation, and its lifecycle is recorded as command.status_changed facts. The envelope is what every command carries: its identity, type, tenant, property, target, handler, idempotency key, requester, expiry, preconditions, evidence and policy. The data of a command is defined by its type. A command is evaluated in full before anything is sent; whatever is not allowed is refused.",
    "type": "object",
    "required": [
      "hoscommandversion",
      "command_id",
      "type",
      "hostenant",
      "hosproperty",
      "target",
      "handler",
      "idempotency_key",
      "requester",
      "requested_at",
      "expires_at",
      "preconditions",
      "evidence",
      "policy",
      "data"
    ],
    "properties": {
      "hoscommandversion": {
        "const": "0.2",
        "description": "HOS version the command conforms to. A document with this member is a command."
      },
      "command_id": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Identity of the command, unique within its tenant."
      },
      "type": {
        "type": "string",
        "pattern": "^[a-z]+(?:_[a-z]+)*(?:\\.[a-z]+(?:_[a-z]+)*){1,2}$",
        "description": "The command type, named domain.resource.verb in the singular."
      },
      "hostenant": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Tenant: the security, policy and data-autonomy boundary. The target and the handler's properties must belong to it."
      },
      "hosproperty": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Property the command acts in."
      },
      "target": {
        "type": "string",
        "pattern": "^(?:stay|task):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "The typed HOS entity the command acts on, such as stay:stay_1042."
      },
      "handler": {
        "type": "string",
        "format": "uri",
        "description": "The system that is the authority for the command and executes it. It must be the producer of a verified manifest that declares the command type with authoritative true."
      },
      "idempotency_key": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "With the tenant, the identity of the intent. The same key with the same content returns the existing command; the same key with other content is refused."
      },
      "requester": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/requesterRef",
        "description": "Who asks for the command."
      },
      "requested_at": {
        "type": "string",
        "format": "date-time"
      },
      "expires_at": {
        "type": "string",
        "format": "date-time",
        "description": "After this instant the command is never sent: it expires."
      },
      "preconditions": {
        "type": "array",
        "description": "What must hold, on facts fresh enough, when the command is evaluated, and what the handler reads again at the source just before it sends the request.",
        "items": {
          "oneOf": [
            {
              "type": "object",
              "required": [
                "kind",
                "in"
              ],
              "properties": {
                "kind": {
                  "const": "stay_status"
                },
                "in": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "$ref": "urn:hos:schema:0.1:core#/$defs/stayStatus"
                  }
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "kind",
                "equals"
              ],
              "properties": {
                "kind": {
                  "const": "unit_assignment"
                },
                "equals": {
                  "oneOf": [
                    {
                      "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "The unit the stay is assigned to when the command was decided, or null when it has none. It protects a choice made in the meantime, such as a reassignment by the staff."
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "kind",
                "unit_id",
                "dimension",
                "in"
              ],
              "properties": {
                "kind": {
                  "const": "unit_status"
                },
                "unit_id": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
                },
                "dimension": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatusDimension"
                },
                "in": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "enum": [
                      "vacant",
                      "occupied",
                      "dirty",
                      "clean",
                      "inspected",
                      "operational",
                      "out_of_service",
                      "sellable",
                      "not_sellable",
                      "unknown"
                    ]
                  }
                }
              },
              "allOf": [
                {
                  "if": {
                    "required": [
                      "dimension"
                    ],
                    "properties": {
                      "dimension": {
                        "const": "occupancy"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "in": {
                        "items": {
                          "$ref": "urn:hos:schema:0.1:core#/$defs/occupancyStatus"
                        }
                      }
                    }
                  }
                },
                {
                  "if": {
                    "required": [
                      "dimension"
                    ],
                    "properties": {
                      "dimension": {
                        "const": "housekeeping"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "in": {
                        "items": {
                          "$ref": "urn:hos:schema:0.1:core#/$defs/housekeepingStatus"
                        }
                      }
                    }
                  }
                },
                {
                  "if": {
                    "required": [
                      "dimension"
                    ],
                    "properties": {
                      "dimension": {
                        "const": "maintenance"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "in": {
                        "items": {
                          "$ref": "urn:hos:schema:0.1:core#/$defs/maintenanceStatus"
                        }
                      }
                    }
                  }
                },
                {
                  "if": {
                    "required": [
                      "dimension"
                    ],
                    "properties": {
                      "dimension": {
                        "const": "commercial"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "in": {
                        "items": {
                          "$ref": "urn:hos:schema:0.1:core#/$defs/commercialStatus"
                        }
                      }
                    }
                  }
                }
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "kind",
                "max_age_seconds"
              ],
              "properties": {
                "kind": {
                  "const": "facts_fresh"
                },
                "max_age_seconds": {
                  "type": "integer",
                  "minimum": 1,
                  "maximum": 86400,
                  "description": "The facts the command rests on come from a synchronisation of the authoritative system that succeeded at most this long before the evaluation."
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "kind",
                "equals"
              ],
              "properties": {
                "kind": {
                  "const": "task_priority"
                },
                "equals": {
                  "$ref": "urn:hos:schema:0.1:core#/$defs/taskPriority"
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "kind",
                "in"
              ],
              "properties": {
                "kind": {
                  "const": "task_status"
                },
                "in": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "$ref": "urn:hos:schema:0.1:core#/$defs/taskStatus"
                  }
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "evidence": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "urn:hos:schema:0.2:definitions#/$defs/evidenceRef"
        },
        "description": "The facts and situations the command rests on, which its approver sees before deciding. Provenance is not optional: an action without evidence is refused."
      },
      "policy": {
        "$ref": "urn:hos:schema:0.2:definitions#/$defs/policyRef",
        "description": "The policy the requester evaluated the command against. The policy in force at each evaluation decides."
      },
      "data": {
        "type": "object",
        "description": "The payload. Its shape is defined by type. A command carries only what the handler needs: no name, contact detail or message content."
      }
    },
    "additionalProperties": false
  },
  "command": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:command",
    "title": "HOS Commands 0.2",
    "description": "Draft. The first series of commands: three controlled requests on the command envelope. No command checks a guest in or out, takes a payment or grants a financial compensation. Data objects are closed so that personal data cannot travel unnoticed. Every command carries the preconditions its type requires; a policy may require more.",
    "allOf": [
      {
        "$ref": "urn:hos:schema:0.2:command-envelope"
      },
      {
        "properties": {
          "type": {
            "enum": [
              "stay.unit_assign",
              "housekeeping.task.reprioritize",
              "guest.message.send"
            ]
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "stay.unit_assign"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/stay.unit_assign"
            },
            "target": {
              "pattern": "^stay:"
            },
            "preconditions": {
              "items": {
                "properties": {
                  "kind": {
                    "enum": [
                      "stay_status",
                      "unit_assignment",
                      "unit_status",
                      "facts_fresh"
                    ]
                  }
                }
              },
              "allOf": [
                {
                  "contains": {
                    "required": [
                      "kind",
                      "in"
                    ],
                    "properties": {
                      "kind": {
                        "const": "stay_status"
                      },
                      "in": {
                        "items": {
                          "const": "expected"
                        }
                      }
                    }
                  }
                },
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "unit_assignment"
                      }
                    }
                  }
                },
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "facts_fresh"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "housekeeping.task.reprioritize"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/housekeeping.task.reprioritize"
            },
            "target": {
              "pattern": "^task:"
            },
            "preconditions": {
              "items": {
                "properties": {
                  "kind": {
                    "enum": [
                      "task_priority",
                      "task_status",
                      "facts_fresh"
                    ]
                  }
                }
              },
              "allOf": [
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "task_priority"
                      }
                    }
                  }
                },
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "facts_fresh"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "guest.message.send"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/guest.message.send"
            },
            "target": {
              "pattern": "^stay:"
            },
            "preconditions": {
              "items": {
                "properties": {
                  "kind": {
                    "enum": [
                      "stay_status",
                      "facts_fresh"
                    ]
                  }
                }
              },
              "allOf": [
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "stay_status"
                      }
                    }
                  }
                },
                {
                  "contains": {
                    "required": [
                      "kind"
                    ],
                    "properties": {
                      "kind": {
                        "const": "facts_fresh"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    ],
    "$defs": {
      "stay.unit_assign": {
        "title": "stay.unit_assign",
        "description": "Assign a unit to a stay that has not started. The assignment covers the whole stay, and the unit is not locked: HOS never leaves a lock the guest or the staff did not ask for, and an assignment locked at the source is refused, never unlocked. Its effect is confirmed by a stay.unit_assigned fact of the PMS that is the authority.",
        "x-hos-authority": "PMS",
        "type": "object",
        "required": [
          "stay_id",
          "unit_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The stay to assign. It must be the stay the command targets."
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The unit to assign."
          },
          "reason": {
            "enum": [
              "initial_assignment",
              "upgrade",
              "room_move",
              "readiness",
              "other"
            ],
            "description": "Why, in the terms of stay.unit_assigned. readiness when the command resolves a room readiness risk."
          }
        },
        "additionalProperties": false
      },
      "housekeeping.task.reprioritize": {
        "title": "housekeeping.task.reprioritize",
        "description": "Change the priority of a housekeeping task. Its effect is confirmed by a housekeeping.task.reprioritized fact of the housekeeping system that is the authority.",
        "x-hos-authority": "Housekeeping system",
        "type": "object",
        "required": [
          "task_id",
          "priority"
        ],
        "properties": {
          "task_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The task to reprioritize. It must be the task the command targets."
          },
          "priority": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskPriority",
            "description": "The new priority."
          },
          "due_at": {
            "type": "string",
            "format": "date-time",
            "description": "A new due time, when the command also moves it."
          }
        },
        "additionalProperties": false
      },
      "guest.message.send": {
        "title": "guest.message.send",
        "description": "Send a guest a message from a template of the messaging system. There is no free text: the content stays in the messaging system, which also keeps the consent and the opt-out of the guest. Parameters are bounded, and HOS keeps the template identifier, never the content. Its effect is confirmed by a guest.message.sent fact of the messaging system that is the authority.",
        "x-hos-authority": "Guest messaging system",
        "type": "object",
        "required": [
          "stay_id",
          "channel",
          "template_id"
        ],
        "properties": {
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The stay whose guest receives the message. It must be the stay the command targets."
          },
          "channel": {
            "enum": [
              "sms",
              "email",
              "chat",
              "messaging_app",
              "ota_messaging"
            ],
            "description": "How the message is sent."
          },
          "template_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "A template of the messaging system, which the hotel wrote and approved."
          },
          "parameters": {
            "type": "object",
            "maxProperties": 10,
            "propertyNames": {
              "pattern": "^[a-z][a-z0-9_]{0,31}$"
            },
            "additionalProperties": {
              "oneOf": [
                {
                  "type": "string",
                  "pattern": "^[A-Za-z0-9][A-Za-z0-9 ._:/+-]{0,63}$"
                },
                {
                  "type": "number"
                },
                {
                  "type": "boolean"
                }
              ]
            },
            "description": "Values for the template: short, with no name, contact detail or free text. HOS cannot recognise personal data in a short string; the template's author and the messaging system answer for what the template takes."
          }
        },
        "additionalProperties": false
      }
    }
  },
  "definitions": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:definitions",
    "title": "HOS Commands 0.2 definitions",
    "description": "Draft. The definitions HOS Commands 0.2 adds to HOS Core 0.1, which stays unchanged: command types, the command lifecycle, its reason codes, the references a command, an approval and a policy share, and the preconditions a command may carry.",
    "$defs": {
      "commandType": {
        "enum": [
          "stay.unit_assign",
          "housekeeping.task.reprioritize",
          "guest.message.send"
        ],
        "description": "The command types of the first series. Every other type is refused: HOS Commands 0.2 defines controlled requests, not a general privilege to automate."
      },
      "commandStatus": {
        "enum": [
          "proposed",
          "pending_approval",
          "approved",
          "executing",
          "succeeded",
          "rejected",
          "failed",
          "expired",
          "cancelled"
        ],
        "description": "The lifecycle of a command. succeeded, rejected, failed, expired and cancelled are final: a correction is a new command."
      },
      "commandReason": {
        "enum": [
          "not_permitted",
          "undeclared_capability",
          "unverified_manifest",
          "outside_tenant",
          "idempotency_conflict",
          "approval_invalid",
          "approval_expired",
          "command_expired",
          "precondition_failed",
          "stale_facts",
          "locked_at_source",
          "rejected_by_approver",
          "rejected_by_source",
          "source_unavailable",
          "confirmation_mismatch",
          "cancelled_by_requester",
          "suspended"
        ],
        "description": "Why a command ended without succeeding. rejected means refused before execution (policy, capability, tenant, approver); failed means approved but not achieved."
      },
      "commandDigest": {
        "type": "string",
        "pattern": "^sha-256:[0-9a-f]{64}$",
        "description": "sha-256: followed by the SHA-256 of the canonical form (RFC 8785) of a command, in lower-case hexadecimal. An approval carries the digest of the command its approver saw: a command changed afterwards no longer matches."
      },
      "policyRef": {
        "type": "object",
        "description": "The version of the policy in force when a command or an approval was evaluated.",
        "required": [
          "policy_id",
          "version"
        ],
        "properties": {
          "policy_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "version": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          }
        },
        "additionalProperties": false
      },
      "evidenceRef": {
        "type": "object",
        "description": "A fact or a situation a command rests on: where it comes from and its id.",
        "required": [
          "source",
          "id"
        ],
        "properties": {
          "source": {
            "type": "string",
            "format": "uri"
          },
          "id": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      },
      "requesterRef": {
        "type": "string",
        "pattern": "^(?:user|integration):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "Who asks for a command: user (a staff member) or integration (an application, a future agent, which only proposes), with a pseudonymous, tenant-scoped reference. Never a name or contact detail."
      },
      "approverRef": {
        "type": "string",
        "pattern": "^user:[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "Who approves a command: always a person, with a pseudonymous reference. An integration never approves."
      },
      "approverRole": {
        "type": "string",
        "pattern": "^[a-z][a-z0-9_]{0,63}$",
        "description": "A role of the tenant, such as front_office_manager. A policy names the roles that may approve; the approval records the role its approver decided under."
      },
      "preconditionKind": {
        "enum": [
          "stay_status",
          "unit_assignment",
          "unit_status",
          "facts_fresh",
          "task_priority",
          "task_status"
        ],
        "description": "The kinds of precondition a command may carry."
      },
      "confirmationEventType": {
        "enum": [
          "stay.unit_assigned",
          "housekeeping.task.reprioritized",
          "guest.message.sent"
        ],
        "description": "The event types that confirm a command: the facts of the authoritative system that show the effect."
      }
    }
  },
  "event-envelope": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:event-envelope",
    "title": "HOS Events 0.2 envelope profile",
    "description": "Draft. The HOS Events 0.1 envelope profile for the event types HOS Events 0.2 adds. CloudEvents 1.0 in structured JSON mode with HOS extension attributes; the only differences from 0.1 are hosschemaversion, which is 0.2, and the command: subject. Event types of HOS Events 0.1 keep their 0.1 envelope: a 0.1 event is the same bytes in a 0.1 and in a 0.2 stream. Attribute names follow CloudEvents rules: lower-case letters and digits, at most 20 characters, scalar values only.",
    "type": "object",
    "required": [
      "specversion",
      "id",
      "source",
      "type",
      "time",
      "datacontenttype",
      "hosschemaversion",
      "hosrecordedat",
      "hostenant",
      "hosproperty",
      "hospropertytimezone",
      "hossubjects",
      "data"
    ],
    "propertyNames": {
      "pattern": "^[a-z0-9]{1,20}$"
    },
    "properties": {
      "specversion": {
        "const": "1.0",
        "description": "CloudEvents specification version."
      },
      "id": {
        "type": "string",
        "minLength": 1,
        "description": "Producer-scoped, immutable event identity. With source, it is the duplicate key: a redelivered event keeps its id."
      },
      "source": {
        "type": "string",
        "format": "uri",
        "description": "The producer. Must equal the producer declared in its Event Producer manifest."
      },
      "type": {
        "type": "string",
        "pattern": "^[a-z]+(?:_[a-z]+)*(?:\\.[a-z]+(?:_[a-z]+)*){1,2}$",
        "description": "Vendor-neutral HOS event type, named domain.resource.past_tense in the singular."
      },
      "time": {
        "type": "string",
        "format": "date-time",
        "description": "When the fact occurred, when known. Otherwise the best time the producer has, qualified by hostimebasis."
      },
      "datacontenttype": {
        "const": "application/json",
        "description": "HOS 0.2 data is always JSON."
      },
      "dataschema": {
        "type": "string",
        "format": "uri",
        "description": "Optional reference to the schema of data."
      },
      "hosschemaversion": {
        "const": "0.2",
        "description": "HOS version the event conforms to."
      },
      "hosrecordedat": {
        "type": "string",
        "format": "date-time",
        "description": "When the HOS implementation (producer or adapter) recorded the event. HOS always carries it."
      },
      "hostimebasis": {
        "enum": [
          "occurred",
          "modified",
          "recorded"
        ],
        "description": "What time represents. Absent means occurred. modified means the source's last modification of the entity, when it does not date the change itself: the fact occurred at or before time. recorded means the occurrence time is unknown and time is when the producer or adapter recorded the fact."
      },
      "hostenant": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Tenant: the security, policy and data-autonomy boundary."
      },
      "hosproperty": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
        "description": "Property the fact belongs to: the operating context."
      },
      "hospropertytimezone": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/ianaTimezone",
        "description": "IANA time zone of the Property. Local times are derived from it, never assumed."
      },
      "hosbusinessdate": {
        "type": "string",
        "format": "date",
        "description": "Local operating (business) date the fact belongs to, when it matters. It can differ from the calendar date of time."
      },
      "hossubjects": {
        "type": "string",
        "pattern": "^(?:tenant|property|unit|reservation|stay|task|guest|message|command):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}(?: (?:tenant|property|unit|reservation|stay|task|guest|message|command):[A-Za-z0-9][A-Za-z0-9._~-]{0,127})*$",
        "description": "Typed HOS entity references implicated by the fact, as space-separated type:id pairs, for example command:cmd_7f3a91c2 stay:stay_1042. A command is a subject only in HOS Events 0.2. A string because CloudEvents attributes cannot hold arrays."
      },
      "hosdatamode": {
        "enum": [
          "delta",
          "snapshot"
        ],
        "description": "How to read data. Absent means delta. A snapshot must be declared here, be allowed for its type and be sensitivity-classified."
      },
      "hossensitivity": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/sensitivityClass",
        "description": "Sensitivity class of data. Required for snapshots."
      },
      "hoscausationsource": {
        "type": "string",
        "format": "uri",
        "description": "Source of the event that caused this one, when known. A command.status_changed to succeeded names the confirming fact; the confirming fact names the command.status_changed to executing."
      },
      "hoscausationid": {
        "type": "string",
        "minLength": 1,
        "description": "Id of the event that caused this one, when known. Used with hoscausationsource."
      },
      "hosactor": {
        "type": "string",
        "pattern": "^(?:user|guest|system|integration):[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$",
        "description": "Who made the change in the producer, when it knows: user (a staff member), guest, system (the producer itself) or integration (another system through its API), with a pseudonymous, producer-scoped reference, for example user:staff_k3. Never a name or contact detail."
      },
      "data": {
        "type": "object",
        "description": "The normalized payload. Its shape is defined by type; vendor detail goes in data.extensions under an inverted domain namespace."
      }
    },
    "dependentRequired": {
      "hoscausationid": [
        "hoscausationsource"
      ],
      "hoscausationsource": [
        "hoscausationid"
      ]
    },
    "if": {
      "required": [
        "hosdatamode"
      ],
      "properties": {
        "hosdatamode": {
          "const": "snapshot"
        }
      }
    },
    "then": {
      "required": [
        "hossensitivity"
      ]
    }
  },
  "events": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:events",
    "title": "HOS Events 0.2",
    "description": "Draft. The three event types HOS Events 0.2 adds to the fifteen of HOS Events 0.1, which stay unchanged and keep hosschemaversion 0.1: the lifecycle of a command, and the two effects no 0.1 event confirms. Facts are immutable. Data objects are closed so that personal or commercial data cannot travel unnoticed. A command.status_changed fact is the record of a transition; the command itself is a document.",
    "allOf": [
      {
        "$ref": "urn:hos:schema:0.2:event-envelope"
      },
      {
        "properties": {
          "type": {
            "enum": [
              "command.status_changed",
              "housekeeping.task.reprioritized",
              "guest.message.sent"
            ]
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "command.status_changed"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/command.status_changed"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "housekeeping.task.reprioritized"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/housekeeping.task.reprioritized"
            }
          }
        }
      },
      {
        "if": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "guest.message.sent"
            }
          }
        },
        "then": {
          "properties": {
            "data": {
              "$ref": "#/$defs/guest.message.sent"
            }
          }
        }
      },
      {
        "not": {
          "required": [
            "hosdatamode"
          ],
          "properties": {
            "hosdatamode": {
              "const": "snapshot"
            }
          }
        }
      }
    ],
    "$defs": {
      "command.status_changed": {
        "title": "command.status_changed",
        "description": "A command moved from one status to another. The log of these facts is the record of the command: who decided what, when, and why a command ended without succeeding. A gateway publishes the transitions up to approved, the handler the transitions from executing on. The transition to succeeded names the confirming fact in hoscausationsource and hoscausationid; the confirming fact names the transition to executing.",
        "x-hos-family": "Command",
        "x-hos-authority": "Command gateway, then command handler",
        "type": "object",
        "required": [
          "command_id",
          "command_type",
          "previous_status",
          "status"
        ],
        "properties": {
          "command_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "command_type": {
            "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandType"
          },
          "previous_status": {
            "oneOf": [
              {
                "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandStatus"
              },
              {
                "type": "null"
              }
            ],
            "description": "The status before; null for the first transition of a command, to proposed."
          },
          "status": {
            "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandStatus"
          },
          "reason": {
            "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandReason",
            "description": "Why the command ended without succeeding. Required when status is rejected, failed, expired or cancelled, and only then."
          },
          "approval_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "The approval that caused the transition. Required when status is approved, or when the reason is rejected_by_approver."
          },
          "command_digest": {
            "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandDigest",
            "description": "The digest of the command as it was when the transition happened. It ties the record to the exact command content."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "allOf": [
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "proposed"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "type": "null"
                }
              }
            },
            "else": {
              "properties": {
                "previous_status": {
                  "type": "string"
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "pending_approval"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "const": "proposed"
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "approved"
                }
              }
            },
            "then": {
              "required": [
                "approval_id"
              ],
              "properties": {
                "previous_status": {
                  "const": "pending_approval"
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "executing"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "const": "approved"
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "succeeded"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "const": "executing"
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "rejected"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "enum": [
                    "proposed",
                    "pending_approval"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "failed"
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "enum": [
                    "approved",
                    "executing"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "enum": [
                    "expired",
                    "cancelled"
                  ]
                }
              }
            },
            "then": {
              "properties": {
                "previous_status": {
                  "enum": [
                    "proposed",
                    "pending_approval",
                    "approved"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "rejected"
                }
              }
            },
            "then": {
              "required": [
                "reason"
              ],
              "properties": {
                "reason": {
                  "enum": [
                    "not_permitted",
                    "undeclared_capability",
                    "unverified_manifest",
                    "outside_tenant",
                    "idempotency_conflict",
                    "rejected_by_approver",
                    "precondition_failed",
                    "stale_facts",
                    "suspended"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "failed"
                }
              }
            },
            "then": {
              "required": [
                "reason"
              ],
              "properties": {
                "reason": {
                  "enum": [
                    "not_permitted",
                    "undeclared_capability",
                    "unverified_manifest",
                    "outside_tenant",
                    "approval_invalid",
                    "precondition_failed",
                    "stale_facts",
                    "locked_at_source",
                    "rejected_by_source",
                    "source_unavailable",
                    "confirmation_mismatch"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "expired"
                }
              }
            },
            "then": {
              "required": [
                "reason"
              ],
              "properties": {
                "reason": {
                  "enum": [
                    "command_expired",
                    "approval_expired"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "const": "cancelled"
                }
              }
            },
            "then": {
              "required": [
                "reason"
              ],
              "properties": {
                "reason": {
                  "enum": [
                    "cancelled_by_requester",
                    "suspended"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "required": [
                "status"
              ],
              "properties": {
                "status": {
                  "enum": [
                    "proposed",
                    "pending_approval",
                    "approved",
                    "executing",
                    "succeeded"
                  ]
                }
              }
            },
            "then": {
              "not": {
                "required": [
                  "reason"
                ]
              }
            }
          },
          {
            "if": {
              "required": [
                "reason"
              ],
              "properties": {
                "reason": {
                  "const": "rejected_by_approver"
                }
              }
            },
            "then": {
              "required": [
                "approval_id"
              ]
            }
          }
        ],
        "additionalProperties": false
      },
      "housekeeping.task.reprioritized": {
        "title": "housekeeping.task.reprioritized",
        "description": "The priority of a housekeeping task changed. It confirms a housekeeping.task.reprioritize command when it comes from the housekeeping system that is the authority and matches the expected effect. Producers also publish it for changes nobody commanded.",
        "x-hos-family": "Housekeeping",
        "x-hos-authority": "Housekeeping system",
        "type": "object",
        "required": [
          "task_id",
          "previous_priority",
          "priority"
        ],
        "properties": {
          "task_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "unit_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "previous_priority": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskPriority"
          },
          "priority": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/taskPriority"
          },
          "due_at": {
            "type": "string",
            "format": "date-time",
            "description": "The due time of the task after the change, when it has one."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false
      },
      "guest.message.sent": {
        "title": "guest.message.sent",
        "description": "A message was sent to a guest. Only metadata travels, with the template identifier: the content stays in the messaging system. It confirms a guest.message.send command when it comes from the messaging system that is the authority and matches the expected effect.",
        "x-hos-family": "Guest communication",
        "x-hos-authority": "Guest messaging system",
        "type": "object",
        "required": [
          "message_id",
          "channel",
          "template_id",
          "sensitivity"
        ],
        "properties": {
          "message_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "channel": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/messageChannel"
          },
          "template_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "guest_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId",
            "description": "Pseudonymous guest, when the producer has a stable guest identity. A producer without one omits it and never derives one from names or contact details."
          },
          "stay_id": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
          },
          "sensitivity": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/sensitivityClass",
            "description": "Sensitivity class of the message content."
          },
          "extensions": {
            "$ref": "urn:hos:schema:0.1:core#/$defs/extensions"
          }
        },
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "guest_id"
            ]
          },
          {
            "required": [
              "stay_id"
            ]
          }
        ]
      }
    }
  },
  "policy": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:policy",
    "title": "HOS Commands 0.2 policy profile",
    "description": "Draft. The minimal policy HOS Commands 0.2 requires: an allow list of permissions for one tenant, in which anything not permitted is refused. A permission names a command type, the requesters it admits, and a mode: recommend, where a command is proposed and never executed, or approve_and_run, where a person with an admitted role approves and the command is executed. In 0.2 nothing is executed without a human approval. The profile uses the terms of the PRD (tenant, actor, action, target, preconditions, approver role, expiry) so that Trust 0.3 extends it rather than replaces it: a portable policy language, general thresholds and limits, and bounded autonomy are not part of 0.2.",
    "type": "object",
    "required": [
      "hospolicyversion",
      "policy_id",
      "version",
      "tenant",
      "properties",
      "permissions"
    ],
    "properties": {
      "hospolicyversion": {
        "const": "0.2",
        "description": "HOS version the policy conforms to. A document with this member is a policy."
      },
      "policy_id": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
      },
      "version": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$",
        "description": "The version of the policy. A command and an approval record the version they were evaluated against."
      },
      "tenant": {
        "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
      },
      "properties": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
        },
        "description": "The properties of the tenant the policy covers."
      },
      "permissions": {
        "type": "array",
        "description": "What is permitted. A command no permission covers is refused: an empty list refuses everything.",
        "items": {
          "type": "object",
          "required": [
            "type",
            "mode",
            "requesters",
            "command_validity_seconds"
          ],
          "properties": {
            "type": {
              "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandType"
            },
            "properties": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
              },
              "description": "The properties the permission covers; absent, all those of the policy."
            },
            "mode": {
              "enum": [
                "recommend",
                "approve_and_run"
              ],
              "description": "recommend: the command is proposed and stays proposed until it expires or is cancelled. approve_and_run: it goes to approval, then runs."
            },
            "requesters": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "type": "string",
                "pattern": "^(?:user|integration):(?:\\*|[A-Za-z0-9][A-Za-z0-9._~-]{0,127})$"
              },
              "description": "Who may propose the command: a pseudonymous reference, or user:* or integration:* for any requester of that kind."
            },
            "approver_roles": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.2:definitions#/$defs/approverRole"
              },
              "description": "The roles of the tenant that may approve the command."
            },
            "allow_self_approval": {
              "type": "boolean",
              "description": "Whether the requester may approve their own command. Absent means false."
            },
            "command_validity_seconds": {
              "type": "integer",
              "minimum": 60,
              "maximum": 604800,
              "description": "The longest a command may live between its request and its expiry."
            },
            "approval_validity_seconds": {
              "type": "integer",
              "minimum": 60,
              "maximum": 86400,
              "description": "The longest an approval may live between the decision and its expiry."
            },
            "required_preconditions": {
              "type": "array",
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.2:definitions#/$defs/preconditionKind"
              },
              "description": "The kinds of precondition a command must carry on top of those its type requires."
            },
            "limits": {
              "type": "object",
              "properties": {
                "max_per_hour": {
                  "type": "integer",
                  "minimum": 1,
                  "description": "The most commands of this type that may be proposed for the tenant in an hour."
                },
                "max_per_target_per_day": {
                  "type": "integer",
                  "minimum": 1,
                  "description": "The most commands of this type that may target the same entity in a day."
                }
              },
              "additionalProperties": false
            }
          },
          "if": {
            "required": [
              "mode"
            ],
            "properties": {
              "mode": {
                "const": "approve_and_run"
              }
            }
          },
          "then": {
            "required": [
              "approver_roles",
              "approval_validity_seconds"
            ]
          },
          "additionalProperties": false
        }
      }
    },
    "additionalProperties": false
  },
  "producer-manifest": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:hos:schema:0.2:producer-manifest",
    "title": "HOS 0.2 Producer manifest",
    "description": "Draft. A producer's versioned statement of exactly what it produces, exposes and authoritatively controls. It is the HOS 0.1 Event Producer manifest, with the command types the system accepts and executes as the authority, and the facts that confirm each of them. A system that accepts no command declares none. Public systems publish it at /.well-known/hos/manifest.json; private systems may use a configured authenticated URL. At most one producer is authoritative for a given event type and dimension (or command status) at a property. The manifest carries no signature: its producer signs it with a detached JWS, published beside it at /.well-known/hos/manifest.jws, and publishes its keys at /.well-known/hos/jwks.json. A command is sent only to a handler whose manifest is signed, verified, unexpired and declares the command type with authoritative true.",
    "type": "object",
    "required": [
      "hosmanifestversion",
      "producer",
      "name",
      "organization",
      "system_role",
      "property_ids",
      "events",
      "delivery",
      "replay",
      "retention",
      "limitations"
    ],
    "properties": {
      "hosmanifestversion": {
        "const": "0.2"
      },
      "producer": {
        "type": "string",
        "format": "uri",
        "description": "Must equal the source attribute of every event the producer emits."
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "organization": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": false
      },
      "system_role": {
        "enum": [
          "pms",
          "housekeeping",
          "maintenance",
          "messaging",
          "integration",
          "other"
        ]
      },
      "property_ids": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "$ref": "urn:hos:schema:0.1:core#/$defs/hosId"
        }
      },
      "entities": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "enum": [
            "Tenant",
            "Property",
            "Unit",
            "MaintenanceWindow",
            "Reservation",
            "Stay",
            "Task",
            "Guest",
            "Message"
          ]
        },
        "description": "Core entities the producer exposes."
      },
      "events": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": [
            "type",
            "authoritative"
          ],
          "properties": {
            "type": {
              "enum": [
                "reservation.created",
                "reservation.updated",
                "reservation.cancelled",
                "stay.expected",
                "stay.checked_in",
                "stay.check_in_reverted",
                "stay.checked_out",
                "stay.unit_assigned",
                "stay.unit_unassigned",
                "unit.status_changed",
                "unit.maintenance_scheduled",
                "unit.maintenance_cancelled",
                "housekeeping.task.created",
                "housekeeping.task.completed",
                "guest.message.received",
                "command.status_changed",
                "housekeeping.task.reprioritized",
                "guest.message.sent"
              ]
            },
            "dimensions": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.1:core#/$defs/unitStatusDimension"
              },
              "description": "For unit.status_changed: the dimensions this declaration covers."
            },
            "authoritative": {
              "type": "boolean",
              "description": "true when this producer is the system of record for the event type (and dimensions) at the declared properties. Non-authoritative facts are recorded and shown, never merged into the authoritative value."
            },
            "snapshot": {
              "type": "boolean",
              "description": "true when the producer may send this type in snapshot mode. Snapshots from a producer that does not declare them are ignored."
            },
            "note": {
              "type": "string"
            },
            "statuses": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandStatus"
              },
              "description": "For command.status_changed: the statuses this declaration covers. A gateway declares the transitions up to approved, a handler the transitions from executing on."
            }
          },
          "additionalProperties": false
        }
      },
      "commands": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "object",
          "required": [
            "type",
            "authoritative",
            "targets",
            "preconditions",
            "idempotency_window_seconds",
            "confirmation"
          ],
          "properties": {
            "type": {
              "$ref": "urn:hos:schema:0.2:definitions#/$defs/commandType"
            },
            "authoritative": {
              "type": "boolean",
              "description": "true when this system is the authority that executes the command type at the declared properties. A command is sent only to a handler that declares it authoritative."
            },
            "targets": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "enum": [
                  "Stay",
                  "Task"
                ]
              },
              "description": "The Core entities the command may target."
            },
            "preconditions": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "urn:hos:schema:0.2:definitions#/$defs/preconditionKind"
              },
              "description": "The kinds of precondition the handler checks at the source just before it sends the request."
            },
            "idempotency_window_seconds": {
              "type": "integer",
              "minimum": 60,
              "description": "How long the handler remembers an idempotency key, in seconds."
            },
            "confirmation": {
              "type": "object",
              "required": [
                "events",
                "max_delay_seconds",
                "attribution"
              ],
              "properties": {
                "events": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "$ref": "urn:hos:schema:0.2:definitions#/$defs/confirmationEventType"
                  },
                  "description": "The event types of the authoritative system that confirm the command. Each is declared authoritative in events."
                },
                "max_delay_seconds": {
                  "type": "integer",
                  "minimum": 1,
                  "description": "How long after the request a confirming fact is awaited before the confirmation is late. A late confirmation does not fail the command: a person decides."
                },
                "attribution": {
                  "enum": [
                    "effect",
                    "source"
                  ],
                  "description": "How a confirming fact is tied to a command. effect: by the expected effect (the stay, the unit, the window), so an identical change made by hand in the window counts as confirmation: true of the state, not of the author. source: the source system says which application made the change."
                }
              },
              "additionalProperties": false
            },
            "limits": {
              "type": "object",
              "properties": {
                "max_per_minute": {
                  "type": "integer",
                  "minimum": 1
                }
              },
              "additionalProperties": false,
              "description": "Limits the handler enforces on its own, for example those of the system's API."
            },
            "note": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "description": "The command types this system accepts and executes. Empty or absent: it accepts none."
      },
      "delivery": {
        "type": "object",
        "required": [
          "mechanisms",
          "guarantee",
          "ordering"
        ],
        "properties": {
          "mechanisms": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "enum": [
                "webhook",
                "polling",
                "stream",
                "file"
              ]
            }
          },
          "guarantee": {
            "const": "at-least-once",
            "description": "HOS delivery is at-least-once; consumers deduplicate on source and id."
          },
          "ordering": {
            "enum": [
              "none",
              "per-subject",
              "total"
            ],
            "description": "Ordering is never global; it holds only as declared here."
          }
        },
        "additionalProperties": false
      },
      "replay": {
        "type": "object",
        "required": [
          "supported"
        ],
        "properties": {
          "supported": {
            "type": "boolean"
          },
          "window_days": {
            "type": "integer",
            "minimum": 0,
            "description": "A certified Event Producer profile provides at least 30 days."
          },
          "format": {
            "const": "jsonl",
            "description": "Replays are JSON Lines: one event per line, in delivery order."
          }
        },
        "additionalProperties": false
      },
      "retention": {
        "type": "object",
        "required": [
          "event_days"
        ],
        "properties": {
          "event_days": {
            "type": "integer",
            "minimum": 0
          },
          "command_days": {
            "type": "integer",
            "minimum": 0,
            "description": "How long the command journal is kept, when the producer keeps one. The real retention, never the intended one."
          }
        },
        "additionalProperties": false
      },
      "limitations": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "description": "Known gaps, unsupported states and access constraints, stated explicitly. Empty only when there are none."
      }
    },
    "additionalProperties": false
  }
};
