import { existsSync, readdirSync, readFileSync } from "node:fs";

// Generates the conformance scenarios the CLI embeds, so hos conformance runs offline, from the published corpus in
// public/spec/0.1/conformance: every directory with a scenario.json.

const corpus = new URL("../../../public/spec/0.1/conformance/", import.meta.url);
const readJson = (file: string) => JSON.parse(readFileSync(new URL(file, corpus), "utf8"));

export function generate(): Record<string, string> {
  const ids = readdirSync(corpus)
    .filter((entry) => existsSync(new URL(`${entry}/scenario.json`, corpus)))
    .sort();
  const scenarios = Object.fromEntries(
    ids.map((id) => {
      const scenario = readJson(`${id}/scenario.json`);
      const events = readFileSync(new URL(`${id}/${scenario.files.events}`, corpus), "utf8")
        .split(/\r?\n/)
        .filter((line) => line.trim())
        .map((line) => JSON.parse(line));
      const manifests = scenario.files.producers.map((file: string) => readJson(`${id}/${file}`));
      return [id, { scenario, manifests, events, expected: readJson(`${id}/${scenario.files.expected}`) }];
    }),
  );
  return {
    "src/scenarios.generated.ts": `// Generated by scripts/generate.ts from public/spec/0.1/conformance. Do not edit: change the published files and run
// npm run generate -w @hos-ai/cli.

import type { ConformanceScenario, ExpectedOutcome, HosFact, ProducerManifest } from "@hos-ai/sdk";

export type EmbeddedScenario = { scenario: ConformanceScenario; manifests: ProducerManifest[]; events: HosFact[]; expected: ExpectedOutcome };

export const scenarios: Record<string, EmbeddedScenario> = ${JSON.stringify(scenarios, null, 2)};
`,
  };
}
